### ISSUE TITLE
Refreshing entire map

### ISSUE THREAD

**Issue by razvan925** [neveldo/jQuery-Mapael#104]
Hello,

Is there a way to refresh the entire map without reloading the web page or to delete all the links and plots existing on the map, not knowing how many plots or links are there?

Thank you,
Razvan

**Comment by Indigo744** [comment]
Hello,
Usually, when you want to delete plots/links, you need to call the `update` event and passing a list of plots/links names in `deletedPlots` and `deletedLinks`.
There is sadly no quick way to delete all plots or links without keeping a list of them somewhere.

Can you give a little more context on what you are trying to achieve? Why is this needed?
This feature could be added, there is an release coming with some new stuff :-)

Or maybe @neveldo will be able to think of a workaround.

**Comment by razvan925** [comment]
I am dynamically adding and deleting a number of links and plots on/from the map and at some point i want to refresh the map in order to start the whole process again but with different data. The links and plots that have to be added or deleted are pre-selected and time scheduled (i used setTimeout) so i tried to stop all the setTimeouts with clearTimeout, the process stops fine, but some links just won't dissapear.

**Comment by Indigo744** [comment]
I see. Can't you keep a record of all plots/links added (in a global array of your process, for instance) that you update on add/remove, and that you pass to the `update` event when you want to delete all?

Actually, you would not even have to remove any name from the array. Just keep a record of *all* the plots/links added, and pass it to the event. If the plots or links doesn't exists, it will do nothing.

When refreshing is done, empty the array and start again.

**Comment by razvan925** [comment]
I thought that if i pass the update function an array with elements that don't exist on the map it would throw and error or someting. I'll try this solution and come back with the result. Thanks

**Comment by Indigo744** [comment]
I just implemented this feature in this PR.
Can you give it a try? 
The updated file can be found here: https://github.com/Indigo744/jQuery-Mapael/blob/Indigo744-patch-update-delete-all-links-plots/js/jquery.mapael.js

**Comment by razvan925** [comment]
It works like a charm. Thank you :D

**Comment by Indigo744** [comment]
Please close the point if it's ok :-)
