### ISSUE TITLE
Legend : hide elements on click should take into account all the legends (bug)

### ISSUE THREAD

**Issue by neveldo** [neveldo/jQuery-Mapael#108]
In case of multiple legends and multiple valued plots or areas, when a user click on a legend item to hide the related elements, the hiding process should take into account the state of the other legends.

Example : http://jsfiddle.net/neveldo/xd2azoxL/

When you click on the "> 100 000" slice, Seattle is hidden. When you click on "> 500" slice, Seattle stays hidden, all is ok until here.

But if I click again on the "> 500 slice", Seattle is shown but it shouldn't because the "> 100 000" slice is still "clicked".

**Comment by Indigo744** [comment]
It was easier than expected... :-)

**Comment by neveldo** [comment]
Indee, thank you for the fix !
