### ISSUE TITLE
how get proper coordinates to new map

### ISSUE THREAD

**Issue by mancho-ged** [neveldo/jQuery-Mapael#11]
I am trying to make map of custom country (Tbilisi, georgia) with mapael. Everything is ok, but the plots. I cannot coordinate them properly with latitude and languitude. How can I do this? I tryed to do according to usa map but it don't work :( where and what I should put?

saqartvelos_regionebi : {
					width : 844.8, 
					height : 469.2,
					latLngToGrid: function(lat, lng, phi1, phi2, midLng, scale) {
						var pi =Math.PI
							, midLat = (phi1 + phi2) / 2
							, n, tmp1, tmp2, tmp3, x, y, p;

						n = (Math.sin(phi1 / 180 * pi) + Math.sin(phi2 / 180 * pi)) / 2;
						tmp1 = Math.sqrt(Math.cos(phi1 / 180 * pi)) + 2 * n * Math.sin(phi1 / 180 * pi);
						tmp2 = scale * Math.pow(tmp1 - 2 * n * Math.sin(midLat / 180 * pi),0.5) / n;
						tmp3 = n * (lng - midLng);
						p = scale * Math.pow(tmp1 - 2 * n * Math.sin(lat / 180 * pi),0.5) / n;
						x = p * Math.sin(tmp3 / 180 * pi);
						y = tmp2 - p * Math.cos(tmp3 / 180 * pi);
						
						return([x,y]);
					},
					getCoords : function (lat, lon) {
						var coords = {};
						if(lat > 43.582132) { // alaska

							// these are guesses
							var phi1= 15; // standard parallels
							var phi2= 105;
							var midLng = 43.5;
							var scale = 530;
							coords = this.latLngToGrid(lat, lon, phi1, phi2, midLng, scale);
							xOffset = 190;
							yOffset = 543;
							scaleX= 1;
							scaleY= -1;

						} else if (lon < 40) { // hawaii
							// Lat: 18°?55' N to 28°?27' N, Lng:154°?48' W to 178°?22' W
							// (225, 504) to (356, 588) on map

							// these are guesses
							var phi1= 0; // standard parallels
							var phi2= 26;
							var midLng = 42;
							var scale = 1280;
							coords = this.latLngToGrid(lat, lon, phi1, phi2, midLng, scale);
							xOffset = 115;
							yOffset = 723;
							scaleX= 1;
							scaleY= -1;
						} else {
							xOffset = -17;
							yOffset = -22;
							scaleX = 10.05;
							scaleY = 6.26;

							coords[0] = 50.0 + 124.03149777329222 * ((1.9694462586094064-(lat* Math.PI / 180)) * Math.sin(0.6010514667026994 * (lon + 96) * Math.PI / 180));
							coords[1] = 50.0 + 1.6155950752393982 * 124.03149777329222 * 0.02613325650382181 - 1.6155950752393982* 124.03149777329222 * (1.3236744353715044- (1.9694462586094064-(lat* Math.PI / 180)) * Math.cos(0.6010514667026994 * (lon + 96) * Math.PI / 180));
						}
						return {x : (coords[0] * scaleX + xOffset), y : (coords[1] * scaleY + yOffset)};
					},

**Comment by jadirpuppin** [comment]
Com todas as explicações, ainda estou com dúvidas. Talvez por não dominar a língua inglesa. 
Por acaso existe algum passo a passo com screenshot para criar um mapa personalizado? 
Transformei o arquivo SVG em Mapel, peguei as informações de Latitude no Google maps, mas não sei como usa-los, apesar de estar explicado aí em cima. Se puder me ajudar, agradeço. Preciso muito disso.

**Comment by neveldo** [comment]
Hello,

Sorry, I don't speak portuguese, but here is a complete tutorial to create your own map for Mapael : http://www.vincentbroute.fr/mapael/create-map.php . I hope it will help you !

**Comment by jadirpuppin** [comment]
Can anyone help me generate the coordinates with the data below?

![espirito santo - google maps](https://cloud.githubusercontent.com/assets/7861970/6786731/dbc0d104-d16c-11e4-9973-44c42b7b3a68.png)

(SVG)
https://docs.google.com/file/d/0B8Lb7_0Kk1HRTFo2QmhjMzF2R2M/edit

(CustomMAP.js)
https://drive.google.com/open?id=0B8Lb7_0Kk1HRTFVWVjRLdi1ENTA&authuser=0

**Comment by neveldo** [comment]
Hello,

I think there is an error with the width and height attributes of your map. The width should be close to 800 and the height should be close to 1225. Ensure that you have ungrouped all SVG objects through Inskcape (you shouldn't not have any <g> element in the XML editor), then go to the document properties, and click on "resize page to drawing".

Regarding the getCoords() function, the latitudes and longitudes you've picked up on Google Maps seems to be right. Then , you just have to do the same thing on your mapael map. You can position points by x and y on your map. You have to find the x coordinates  that match the west and east longitudes you have picked up, and do the same for the north and south latitudes.

	$(function(){
		$(".container1").mapael({
			map : {
				// Set the name of the map to display
				name : "france_departments",
			},
            plots : {
              p1 : {
                x : 100,
                y : 50,
                size : 5
              }
            }
		});
	});

Then, you just have to fill this form in order to get the getCoords() function content : http://www.vincentbroute.fr/mapael/getcoords.php . It just resolves the equations with two unknowns.

**Comment by jadirpuppin** [comment]
All right. Thank you very much.

**Comment by Indigo744** [comment]
All issue seems to be resolved. This thread will be closed. Feel free to open a new issue if you have any problem. Thanks!
