### ISSUE TITLE
Suggestion: provide your todo list in readme.md

### ISSUE THREAD

**Issue by Indigo744** [neveldo/jQuery-Mapael#126]
Hello :-)

Here is a new suggestion! Can you provide a list of your todo list / planned features so that everyone can see what is known and what is unknown ? 

Thanks a lot!

**Comment by neveldo** [comment]
Hello :)

Great idea, I have had in my mind a quite similar one for adding a changelog.md file as in the bower project : https://github.com/bower/bower/blob/master/CHANGELOG.md . We could add in this file the changelog for previous versions (https://github.com/neveldo/jQuery-Mapael/releases) and add a 2.0.0 part with the planned features and non backward-compatible changes. What to you think about it ?

**Comment by Indigo744** [comment]
This is indeed a good way to implements this :-)

**Comment by neveldo** [comment]
I will do it asap :) 

Humm, it seems there is no private messaging on github ! Do you have any email adresse where I could contact you about mapael ? (or you can find my email adress here : http://www.vincentbroute.fr/)

**Comment by Indigo744** [comment]
I was thinking about the idea of putting todo list and planned feature inside the Changelog.
The main problem is that it's not really the place I would look up when searching for a todo.

Looking at bower, they are using a CONTRIBUTING.md file (https://github.com/bower/bower/blob/master/CONTRIBUTING.md). It may be a better place?

Also, I think you should put the licence into a LICENCE file?

**Comment by neveldo** [comment]
Hello,

I agree with you, adding a LICENCE file is a good idea. Regarding the CONTRIBUTING.md file, it seems this is a common place to put the instructions for how to contribute to the project, but I don't think this is a place to put a development todo list. What do you think about using the wiki provided by github for each project ? It would allow us to create multiple page, so we could also use the wiki to describe the internal architecture of the plugin, etc. Some projects like bower seems to use the wiki in this way : https://github.com/bower/bower/wiki . What do you think about it ?

**Comment by Indigo744** [comment]
Nice idea to use the wiki!

**Comment by Indigo744** [comment]
I created a TODO list here: https://github.com/neveldo/jQuery-Mapael/wiki/TODO-list
Add your remaining stuff and we will have a nice list!

**Comment by neveldo** [comment]
Great work, thank you ! For now, I have only added in the todo a weird bug that I have encountered some days ago : https://github.com/neveldo/jQuery-Mapael/issues/136 while checking the dataviz_example.html example.

I close the issue regarding the todo, thank ou again !
