### ISSUE TITLE
Feature for maps: add 'static' elements

### ISSUE THREAD

**Issue by Indigo744** [neveldo/jQuery-Mapael#141]
Issue #49 made me think of a new feature.

Imagine a map where the user wants to add some static SVG elements that should be drawn, but not as part of areas/plots? For instance, if the user wants to always add a [graticule](https://rkpjrhist615.files.wordpress.com/2007/09/lab_3_mollweide_graticule.jpg) or just the border of a non rectangular map (e.g. the contour of a [Robinson projection](http://worldatlas.cccarto.com/files/World_Map_6.jpg)).

As of now, the only option is to use the `beforeInit` or `afterInit` callback and draw using the Raphael paper. But it means duplicating this code between application for a map.

I suggest to add an option `Mapael.maps["my_maps"].static` where a map creator can list all shape it wants to permanently add. Maybe we should also add a `toFront` and `toBack` information for Mapael to know if it should drawn on the front or on the back.

**Comment by neveldo** [comment]
Hello,

I like the idea. Here is a simple way to factorize the code (I haven't tested it but it should work fine) : 

Factorized code called before the initialisation of the  map :

    jQuery.fn.mapael["xxx"].myBeforeInitFct = function(container, paper, areas, plots, options) {
        // ...
    };

Creation of the map :

    $(".myMap").mapael({
        "map": {
            'beforeInit': function(container, paper, areas, plots, options) {
                jQuery.fn.mapael["xxx"].myBeforeInitFct(container, paper, areas, plots, options);
            }
        }
    });

Maybe we could check for the hooks beforeInit() and afterInit()  within the related map object ?

**Comment by Indigo744** [comment]
I like this idea. It will keep the functionality simple (and well-known) yet will allow maps creator to provide extended information.

**Comment by Indigo744** [comment]
After some years, maybe this is quite an edge case that doesn't need any special extension to the library. I'm closing this :)
