### ISSUE TITLE
Questions on Hover attributes

### ISSUE THREAD

**Issue by Indigo744** [neveldo/jQuery-Mapael#180]
Hey,

I was wondering how a user could set an `hoverAttrs` (be for area, plot or link) that is **not** changing a certain attribute.

Let me provide you an example: When over an area, I only want to change the border color. Hence, I would need to update the `stroke` attribute, but not the `fill` attribute. 
In Mapael, since the `fill` attribute is set by default, there is no simple mean to disable it.
The user can only override the `defaultOption`.

I was wondering if we should provide a simple way to define attributes that should not changed on hover, i.e. attributes that should **inherit** from normal attribute.
The value could be actually the string `inherit`. However, the code may be harder to implement.

What do you think about it?

**Comment by neveldo** [comment]
Hello Indigo,

I see the point. You are right, this is a little bit tricky to make hoveAttrs not changing if they have been set through the default options. However, I'm not very fond of the inherit special value to do that, I'm not convinced it will be simpler than overriding the defaultOption part. Or maybe, we could simply remove the hoverAttrs from the defaultOption, so the users could define this option freely ?

**Comment by Indigo744** [comment]
After some thoughts, I think you are write. Let's not make it too complicated :)

We shouldn't change the default options. It's quite nice the way it is!
