### ISSUE TITLE
Problem with zoom after map change

### ISSUE THREAD

**Issue by JhnD** [neveldo/jQuery-Mapael#184]
Hello,

I'm creating a web application where you can load map dynamically using mapael and another menu plugin.
I edit the function $(function(){$(".mapcontainer").mapael({ to have a return instead.

After that, each time i click a button on the menu, i call the function which change my ".mapcontainer" tag by a new map.

The problem is after the update, i can't use the zoom function.

Can you say what's wrong ?

[I will post the code later]

**Comment by JhnD** [comment]
And now the code,

My function is
```
function getMap() {
    $maparea = $(".mapcontainer");
    $maparea.mapael({
        map: {...
        }
    });
}
```
and i call the function with
```
$("#building").on('click', 'a', function (){
        var navigation = $(this).attr('href').substring(1);
        eval(navigation + "()");
});
```
 eval(navigation + "()") call the function but break the zoom option after update

**Comment by dharmeshvaghani** [comment]
I am also facing a similar situation. I am periodically refreshing the map with updated data.  As soon as the refresh happens the zoom stops working and starts failing.

**Comment by neveldo** [comment]
Hello,

@dharmeshvaghani , Do you refresh the map by triggering an 'update' event on the map ? In this case, the zoom feature should work fine. Here is an example where the map with the zoom feature activated, and with some updates performed : http://jsfiddle.net/neveldo/TKUy4/ . Maybe you are facing a different issue. Could you open a new thread with an online example of you code that shows the issue (it could be a JSFiddle for example).

@JhnD : Which version of Mapael  are you using ? Is it a regular one, or are you using the code of the master branch ? Could you also provide a complete example that show the issue, maybe on JSFiddle ?

**Comment by dharmeshvaghani** [comment]
We are not using the update event to update the map. What we have in our situation is periodically we need to create a new map based on some REST response, so it could be a usa_states map, france map, world map etc. So we call the  $(".mapcontainer").mapael({...}) method periodically. And what happens is that the map is rendered and we can zoom it but as soon as the next refresh happens where the $(".mapcontainer").mapael({...}) is called again the zoom functionality stops working. To simulate this problem I have taken an example(test_leak/test_new_maps.html) from git test-leak branch and modified as per my requirement so you could understand the problem.

Steps to reproduce :
When click on zoomin button then map got resized. After interval(2000ms) then map is refreshed and automatically got resized. 
Now click on zoomin button, error message("Cannot read property 'map' of undefined") is getting displayed in console.

Here I'm attached text_zoom_maps.zip.
[test_zoom_maps.zip](https://github.com/neveldo/jQuery-Mapael/files/93918/test_zoom_maps.zip)

**Comment by JhnD** [comment]
Hello !

Finally, i found a solution, here is the complete example:

For the map, you have to create 2 js file:

[mapname].js:
```
(function (factory) {
    if (typeof exports === 'object') {
        // CommonJS
        module.exports = factory(require('jquery'), require('mapael'));
    } else if (typeof define === 'function' && define.amd) {
        // AMD. Register as an anonymous module.
        define(['jquery', 'mapael'], factory);
    } else {
        // Browser globals
        factory(jQuery, jQuery.mapael);
    }
}(function ($, Mapael) {

    "use strict";
    
    $.extend(true, Mapael, 
        {
            maps : {
                mapname : {
                    width : 3804.375,
                    height : 1365,
                    getCoords : function (lat, lon) {

                    },
                    elems : {
						...
                    }
                }
            }
        }
    );

    return Mapael;

}));
```

And [mapname]_params.js:
```
function getMapName() {
    $mapcontent = $(".content");
    $maparea = $(".mapcontainer");
    var html =  '<div  class="mapcontainer">' + 
                    '<div class="map">' +
                    '<span>Alternative content for the map</span>' +
                    '</div>' +
                '</div>';
    
    $maparea.remove();
    $mapcontent.append(html);
    
    $maparea = $(".mapcontainer");
    
    $maparea.mapael({
        map: {
            name:"mapname"
                // Enable zoom on the map
                ,
            zoom: {
                enabled: true,
                maxLevel: 15
            }
            // Set default plots and areas style
            ,
            defaultPlot: {
                attrs: {
                    fill:"#004a9b",
                    opacity: 0.6
                },
                attrsHover: {
                    opacity: 1
                },
                text: {
                    attrs: {
                        fill:"#505444"
                    },
                    attrsHover: {
                        fill:"#000"
                    }
                }
            },
            defaultArea: {
                attrs: {
                    fill:"#f4f4e8",
                    stroke:"#ced8d0"
                },
                attrsHover: {
                    fill:"#a4e100"
                },
                text: {
                    attrs: {
                        fill:"#505444"
                    },
                    attrsHover: {
                        fill:"#000"
                    }
                }
            }
        },

        // Customize some areas of the map
        areas: {...}
    });
}
```
And now you have just to call the function associated with the map (remember to include both js files),
With a menu and jquery for example:
```
    $("#building").on('click', 'a', function (){
        navigation = $(this).attr('href').substring(1);
        eval(navigation + "()");
    });
```

You can suggest a better example or close the issue if you want.


Thank you again.

**Comment by neveldo** [comment]
@dharmeshvaghani : Thanks for providing a code example that shows the issue. I have made a little fix on the destroy function that should solve the issue : https://github.com/neveldo/jQuery-Mapael/commit/ad91482282bddbd979d9cf87e48b349e887766ca . The error occured because the listeners for the zoom event from the previous loaded maps were not properly detached from the container.

@JhnD , I'm glad you found a solution by yourself, thank you for having shared it ! I think this is the proper way to deal with maps refreshs with the last stable version of Mapael. Here is a JSFiddle example I have made a few weeks ago, for another usecase : http://jsfiddle.net/neveldo/h9e2dgeL/ . You can see that this is almost the same solution I have used here.
