### ISSUE TITLE
tooltip persistence

### ISSUE THREAD

**Issue by muckydog** [neveldo/jQuery-Mapael#187]
Hello Vincent,

Thank you for this fantastic tool! I'm using it here in a very simple setup: http://www.geopd.org/newsite/membership.php

All is going according to plan, except that my tool tips are not disappearing on mouse out. Possibly related, I find the mouse scroller zoom in/out does not work on my map as it does in your examples.

I've gone through everything with a fine tooth comb, compared to your examples and am baffled. Wonder if you might be able to have a quick look and suggest where I've gone off the rails?

Many thanks.

**Comment by dnsBlah** [comment]
Hi Muckydog, I find that the scrolling is working on Firefox, Safari and IE

Please note down your browser type.

Yes the tool-tips are not disappearing.
@Indigo744  Maybe this is related due the
$(".mapcontainer svg").mousemove(function () { ... }
Maybe it overwrites something regarding the tool-tips ?

**Comment by muckydog** [comment]
Scroller issue was a silly mistake at my end--now fixed!

Browser: Safari 9.0.3 & Firefox 43.0.4

@Indigo744 any suggestions?

Thanks

**Comment by neveldo** [comment]
Hi @muckydog

It seems that you have retrieved the Raphael.js library from its master branch, in which there is a non backward-compatible change regarding the removal of Paper.safari() function, you can see it in your browser console. jQuery Mapael should work fine with Raphaël 2.1.4. It's the same issue than here : https://github.com/neveldo/jQuery-Mapael/issues/59 .

Could you try with Raphaël 2.1.4 and give me a feedback ?

**Comment by Indigo744** [comment]
Actually, it seems to use Mapael 1.1.0 (in master branch version, we use a conditional check for this).

However, the problem lies indeed with the Raphael version.
Can you try with https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.4/raphael-min.js ?

**Comment by muckydog** [comment]
Thanks @Indigo744 that works!

@neveldo, FWIW, I originally downloaded what was labelled Raphael 2.1.4 from the github location you reference in #59. That version results in the persistent tooltip.

Thanks both!

**Comment by Indigo744** [comment]
Yeah, we already discussed this issue with @neveldo... We don't really understand why there is different version of RaphaelJs 2.1.4... 

Glad it works.
