### ISSUE TITLE
Tooltip position

### ISSUE THREAD

**Issue by terry90** [neveldo/jQuery-Mapael#188]
Hello,

The position of the tooltip is never reset for me, when I scroll down the tooltip will appear exactly "the number of pixels I scrolled" too much. 
I tested with a really simple map, the same libs with same version, different versions, I only have a legend and 2 points. I tried to remove every little option like defaultArea and so on..

I have no idea of what is going on.

Here is a screenshot without scrolling.

![noscroll](https://cloud.githubusercontent.com/assets/1941159/12682139/43c12cf0-c6b2-11e5-9ab2-7edb58e02603.png)

Scrolled a bit

![scroll](https://cloud.githubusercontent.com/assets/1941159/12682145/46b05daa-c6b2-11e5-88ac-6cedb222b4f0.png)

Thanks :)

**Comment by terry90** [comment]
Master version is broken.
I'm using 1.1.0 and it is working.

**Comment by neveldo** [comment]
Hi @terry90 ,

The master is not broken but works slightly differently than the 1.1.0 because the map container should be positionned with `position: relative;` CSS. It should fix your issue regarding the tooltip position !

PS : I'm fond of your tooltip content ;)

**Comment by terry90** [comment]
Oh thank you a lot ! This is gonna help me for this version.
Yes, I forgot to change it
