### ISSUE TITLE
[non-issue] manual position - tooltip

### ISSUE THREAD

**Issue by dnsBlah** [neveldo/jQuery-Mapael#189]
Hi Neveldo,

how can I position the plot tooltip ? I don't want it to be relative to my cursor.

I just want it top: 10 left: 10.

adjusting the .mapTooltip does not work

**Comment by neveldo** [comment]
Hi @dnsBlah , 

Have you checked out this JSFiddle example : http://jsfiddle.net/neveldo/b5fj4qod/ ?

I think it doesn't work because the tooltip position is automatically updated on mouseover / mousemove. Maybe a new boolean option `fixed` could be added in order to allow  users to set the tooltip to a fixed position !

**Comment by Indigo744** [comment]
I agree with @neveldo. I will add it to the todo list (https://github.com/neveldo/jQuery-Mapael/wiki/TODO-list).

In the mean time, the workaround above should help you (I actually used it myself in my own project).

**Comment by dnsBlah** [comment]
sorry for the late response guys.
Thanks for the tip, I'm going to try to get this tooltip on the map, top-left corner instead of outside the map

**Comment by dnsBlah** [comment]
By the way, for the todo, is it possible for your json example to put in the 'links' between plots based on the names of the plots?
Im generating the json files through php and currently I got to workaround with the longitudes and longitudes but with the manual links I can out in the names of the plots (maybe its just a encoding I need to change) but just in case :)

**Comment by neveldo** [comment]
Hi @dnsBlah , I don't understand  your issue with the links. The links between two plotted points should work fine : http://jsfiddle.net/neveldo/yckqj78q/ . Maybe you are facing another issue. Could you create a new post with a JSFiddle example that highlights the problem ?

**Comment by dnsBlah** [comment]
Sorry for the late response on this one.
I'm using your first jsFiddle: http://jsfiddle.net/neveldo/b5fj4qod/
But then with an absolute position over the page :)
Thanks!

**Comment by neveldo** [comment]
Hello @dnsBlah , I'm glad it helped you !
