### ISSUE TITLE
Lambert Conformal conic Projection

### ISSUE THREAD

**Issue by Cabalist** [neveldo/jQuery-Mapael#191]
Hey there,

We have a map of Canada derived from the data found on Wikimedia.  It uses Lambert Conformal Conic projects as the Canadian government prefers.   I have done a fair amount of reading on this but walked away a little confused.  The translation for equirectangular seems really easy but I can't find anything specific for LCC.

I have found [this](https://github.com/proj4js/proj4js/blob/d03c1d1dc4fe1a81232c807c4539aff6b0752450/lib/projections/lcc.js) from the Proj4js project.  This seems like the right code but I am struggling to get my variables correct.  Any chance someone on this project could offer some guidance?  

Here is the map js that I am working with:
https://gist.github.com/Cabalist/5bafbacee318606666e4

**Comment by Indigo744** [comment]
Hello,

I have never tried to implement a conic projection. But let's try!

The equation mapping (lon, lat) to (x, y) are here: http://mathworld.wolfram.com/LambertConformalConicProjection.html

However, these (x, y) values are projection specific coordinate. You will then need to translate them to the real (x, y) value of your map.

Anyway, before diving into this, looking at the equations, you will need to know the following constants for your map:
- the reference longitude (lambda_0)
- the reference latitude (phi_0)
- the standard parallels (phi_1 and phi_2)

Without these, you will not be able to project your points.

**Comment by Cabalist** [comment]
This map here looks very similar to the one that I am using:
http://www.statcan.gc.ca/pub/92-195-x/2011001/other-autre/mapproj-projcarte/m-c-eng.htm

The article outlines the following:
"""Standard parallels at 49° N and 77° N are most commonly used."""

I *THINK* reference long/lat are for the center of the map (i.e. 0,0 for x,y) in this case that looks like roughly 64.289334, -93.1220877

**Comment by Indigo744** [comment]
Closing this now, will follow on related PR.
