### ISSUE TITLE
Remove border lines of the world map

### ISSUE THREAD

**Issue by kockok** [neveldo/jQuery-Mapael#193]
I am still scratching my head after reading the docs, so is that possible to remove or blind out the country border lines and just leave the coastal lines present? Thanks.

**Comment by kockok** [comment]
defaultArea: {
        attrs : {
          fill : "#f4f4e8",
          stroke: "#f4f4e8"
        }
      }

**Comment by neveldo** [comment]
Hello,

Thank you for having shared the answer !
