### ISSUE TITLE
Comment accéder au villes de France/Régions avec france_departments

### ISSUE THREAD

**Issue by kdms90** [neveldo/jQuery-Mapael#194]
Bonsoir,
Déjà je tiens à tirer un coup de chapeau pour cet excellent outil.
J'ai commencé avec Mapael pour la manipulation des cartes et j'aimerai savoir comment accéder aux différentes villes/régions de France et si possible, comment mettre en relation certaines villes/régions.

Merci encore.

**Comment by Indigo744** [comment]
Salut,

Qu'entends-tu par "accèder aux villes/régions de France" ?

Toute la documentation Mapael est ici: http://www.vincentbroute.fr/mapael/

L'idée avec Mapael, c'est que tu charges une carte contenant les zones que tu veux afficher (e.g. les départements de France, ou les régions, ou autre...). Regarde du coté du repo mapael-maps (https://github.com/neveldo/mapael-maps) pour une liste des cartes dispo.

Ensuite, sur cette carte, tu places des points via des coordonnées GPS. Ces points peuvent représenter ce que tu veux, des villes par exemple. Voir `plots`.

Une fois que tu as ajouté les villes, tu peux ajouter des liens entre chaque ville. Voir `links`.

**Comment by kdms90** [comment]
Bonsoir. Merci, j'ai suivi tes liens. En fait, je voulais représenter les agences d'une entreprise sur la carte. Maintenant, si possible, j'aimerai modifier la couleur des plots sans utiliser une image cela est-il possible?

Merci encore.

**Comment by Indigo744** [comment]
C'est plutôt simple à mettre en oeuvre si tu as la carte et les coordonnées GPS de tes agences!

Je te conseille de partir d'un exemple simple et d'ajouter à ta convenance.

Par exemple, pour la France, tu peux partir de cet exemple: [Map with some custom plotted cities and areas](http://jsfiddle.net/neveldo/z559d0s2), supprimer la partie "area" et modifier la partie "plots" suivant ton besoin.

**Comment by kdms90** [comment]
Bingo, tout roule. Merci énorment!
