### ISSUE TITLE
Rotate mapael map

### ISSUE THREAD

**Issue by Zulin1** [neveldo/jQuery-Mapael#195]
Hello! Thanks for the great map engine!
Is it possible to rotate whole map? Please, give me some tips on how to do this, if so.

**Comment by Indigo744** [comment]
Hello,

Can you be more precise on what you want to achieve?

If you want the map to be always in a given orientation (i.e. static), then you could just take the initial vector file, rotate it in Inkscape, and convert it to Mapael. This will be the best to do.

Now, if you want to be able to rotate your map dynamically, then it's trickier.
The easiest way would be to use the CSS `transform` property.
Here is a working example with how to do it in JS: http://jsfiddle.net/hhqwcnxt/2/
Note: beware of browser support for transform on SVG. See http://caniuse.com/#feat=transforms2d (known issues).
