### ISSUE TITLE
click eventHandler isn't working with 2.0.0-dev like examples

### ISSUE THREAD

**Issue by billyrennekamp** [neveldo/jQuery-Mapael#202]
Hello,
I'm using  * Version: 2.0.0-dev but the example's click events aren't working on with my plugin. 

i've reproduced this example as well as others:
http://jsfiddle.net/neveldo/TKUy4/

when i looked intot he code i saw that instead of wrapping the new areas info like
    		var updatedOptions = {'areas' : {}, 'plots' : {}};
i needed to wrap them like:

    var updatedOptions = {mapOptions: {'areas' : {}, 'plots' : {}}};

as specified on line 863

    *  opt.mapOptions: options to update for plots and areas

iis the version i'm using just more advanced than the examples? 
is it not supposed to be backwards compatible?

**Comment by billyrennekamp** [comment]
i see now that the examples included with the build reflect the code change but the documentation on the http://www.vincentbroute.fr/mapael/ does not

**Comment by billyrennekamp** [comment]
So since this is actually just a new version does anyone know how to set the map back to the original attributes again? i don't want the user to be able to select more than one country at a time when they click. i can't reference the original area attributes though because it is self referential.

                        var newData = {
	                        	mapOptions : {
		                            'areas' : function(){return this.areas}
		                        }
	                        };

**Comment by neveldo** [comment]
> i see now that the examples included with the build reflect the code change but the documentation on the http://www.vincentbroute.fr/mapael/ does not

Yes, the online examples will be updated when the new version will be released.

Did you found an answer to your last question ? I saw that you have closed the issue, so I think it's ok.
