### ISSUE TITLE
Get current attribute

### ISSUE THREAD

**Issue by alexc101** [neveldo/jQuery-Mapael#214]
Hi,

I'm trying to work with this plugin to retrieve a value of data and insert it into a text box once a region is clicked. So far, I'm not able to get a click event to work! Here is the code =

`	"department-59": {
				value: "59",
				tooltip: {content : "Nord (59)"},
				    eventHandlers: {
                   click: function (e, id, mapElem) {
                        if (mapElem.originalAttr.value === "59") {
                           alert("clicked");
             } 
         }
     }
},`

I'm just wondering what to put instead of originalAttr to retrieve the value inside the nested component, instead of going back to my default settings?

Hope it makes sense, let me know if you would like a plunkr or anything.

Cheers

**Comment by neveldo** [comment]
Hello,

I saw you have just closed your issue, did you found the answer ? Maybe you could share it :)

**Comment by alexc101** [comment]
Hey, sure :)

So, the key was to just ignore the if statement!

`		areas: {
			"department-59": {
				value: "59",
				href: "#",
				tooltip: {
					content: "Nord (59)"
				},
				eventHandlers: {
					click: function(e, id, mapElem) {
						alert("hello");
					}

				}

			},
`

So, for example, this is all I needed for the alert and to make the select menu appear you just need something like;

`"department-75": {
				value: "2268265",
				href : "#",
				tooltip: {content : "Paris (75)"},
				eventHandlers: {
					click: function (e, id, mapElem) {
						$("#paris").css("visibility", "visible");
            			                $(".submit").css("visibility", "visible");
					}
				}`

I think I can improve the solution, but this is where I'm at for the moment!

**Comment by alexc101** [comment]
```
	areas: {
				"department-59": {
					value: "59",
					href: "#",
					tooltip: {
						content: "Nord (59)"
					},
					eventHandlers: {
						click: function(e, id, mapElem) {
							var newData = {
								'areas': {}
							};
							if (mapElem.originalAttrs.fill == "#f4f4e8") {
								newData.areas[id] = {
									attrs: {
										fill: "#0088db"
									}
								};
								$("#nord").css("visibility", "visible")
							}
							else if (mapElem.originalAttrs.fill == "#0088db") {
								newData.areas[id] = {
									attrs: {
										fill: "#f4f4e8"
									}
								};
								$("#nord").css("visibility", "hidden")
							}


							$(".mapcontainer").trigger('update', [newData, false, false, 0]);

						},

					}
				},
```

This is more what I wanted I think,

I think I can still improve it however.

**Comment by neveldo** [comment]
Hello,

Thank you for having shared the solution ! :)

**Comment by alexc101** [comment]
Hi,

I think to make this scalable It would be better to access the map elements from the Parent eventHandler. I was thinking it could be something like this?

````
eventHandlers: {
					click: function(e, id, mapElem) {
						var newData = {
							'areas': {}
						};
						if (mapElem.originalAttrs.fill == "#f4f4e8" && mapElem.elems == "department-59" ) {
							newData.areas[id] = {
								attrs: {
									fill: "#0088db"
								}
							};
							alert("test")
						}
						else if (mapElem.originalAttrs.fill == "#0088db") {
							newData.areas[id] = {
								attrs: {
									fill: "#f4f4e8"
								}
							};
						}
			
						$(".mapcontainer").trigger('update', [newData]);

					}
				},
````

**Comment by neveldo** [comment]
I don't understand well what you want to get as result, could you explain more ? Maybe you could provide a JSFiddle example of your current work.

**Comment by alexc101** [comment]
Hi,

Apologies I think I haven't explained it well at all - I made a post on stackoverflow which may (or may not be a little clearer);

http://stackoverflow.com/questions/36327311/accessing-svg-data-elements-in-jquery

Else, here is a plunk that works;

http://plnkr.co/edit/XXXNQcND54Iw3HirefMc?p=preview

The issue is that I think replicating that much code for each area wouldn't be the best option, so I was hoping to refactor the code so it looked something like this instead, but I'm not sure how I can get it to work;

BROKEN -- 

http://plnkr.co/edit/ExDmSj?p=preview

If you need anything else let me know

**Comment by neveldo** [comment]
Did you found a solution (I saw that you have answered on stackoverflow) ?

For your information, instead of defining a click event handler on each department, you can define only one handler into the "defaultArea" option object in order to factorize the code.

**Comment by alexc101** [comment]
Yes I did!

It was actually quite easy, I should of played around with it a bit more before asking for help I think, not looking at the code for a week seemed to open my eyes though.

I have also created the solution so that I can bring up a different select menu depending on the region clicked whilst keeping the code to a bare minimum - here is the code + plunk;

````
				eventHandlers: {
					click: function(e, id, mapElem) {
						var newData = {
							'areas': {}
						};
						if (mapElem.originalAttrs.fill == "#f4f4e8" && "id[^='department']") {
							newData.areas[id] = {
								attrs: {
									fill: "#0088db"
								}
							};
							$('#' + id).css("visibility", "visible")
						}
						else if (mapElem.originalAttrs.fill == "#0088db" && "id[^='department']") {
							newData.areas[id] = {
								attrs: {
									fill: "#f4f4e8"
								}
							};
							$("#" + id).css("visibility", "hidden")
						}

						$(".mapcontainer").trigger('update', [newData]);

					}
				},
````

http://plnkr.co/edit/2UAl4Yax99dJAPIDWuTy?p=preview

This example will only work for Nord(59)/department-59 and Paris(75)/department-75 however, but I think this is the best solution to run events for each area.

I'm not sure if the best way of displaying the select data is through html, but I think it will be okay for me atm. 

Thanks for helping anyway, and thanks for mapael! it's a great plugin :+1:
