### ISSUE TITLE
Older versions on npm

### ISSUE THREAD

**Issue by shoudaos** [neveldo/jQuery-Mapael#215]
Can you add 0.7.1 version on npmjs, please?

**Comment by neveldo** [comment]
Hello,

Indeed it is possible, but it will be necessary to publish a tag 0.7.2 to include the package.json file (as it has been introduced since the version 1.0.0 of mapael). 

Why can't you use the version 1.0.0 ? There is a very few little non-backward compatible changes from v0.7.1 to 1.0.0.

**Comment by Indigo744** [comment]
0.7.1 is indeed added (https://github.com/neveldo/jQuery-Mapael/releases/tag/0.7.1)

Closing this.

**Comment by Indigo744** [comment]
Sorry, didn't see that package.json is not in 0.7.1. If you have a proper reason for this, reopen this issue.
