### ISSUE TITLE
[No issue] Json import plots & links

### ISSUE THREAD

**Issue by dnsBlah** [neveldo/jQuery-Mapael#217]
Hi all,

I'd like to dynamicly connect my plots.

I'm using one of the samples for json importing plots using:
p.s. I'm using custom 'tooltip' "myText"
[code]`
var tPlots = {};
$.getJSON("plots.json", function (json) {
	$.each(json, function(index, d){
		var plot = {};
		plot.latitude = d.latitude;
		plot.longitude = d.longitude;
		plot.attrs = {
			fill: d.fill
		};
		plot.tooltip= {
			content: d.tooltip
		};
		plot.myText = d.myText;
		tPlots[d.title] = plot;
	});
});`
[/code]
plots.json
[code]`
[{
"title": "WH_Coburg",
"latitude": 50.20312,
"longitude": 10.97428,
"fill": "green",
"opacity": 0.8,
"tooltip": "<span style=\"font-weight:bold;\">WH_Coburg</span>",
"myText": "asdasd"
}, {
"title": "WH_Freiburg",
"latitude": 47.9438,
"longitude": 7.6809,
"fill": "green",
"opacity": 0.8,
"tooltip": "<span style=\"font-weight:bold;\">WH_Freiburg</span>",
"myText": "asdasd"
}]`
[/code]

I also do this with links:
[code]`
var tLinks = {};
$.getJSON("links.json", function (json) {
	$.each(json, function(index, d){
		var link = {};
		link.between = [d.from,d.to];
		link.tooltip = {
			content: d.tooltip
		};
		link.attrs = {
			stroke: d.strokeColor
		};
		tLinks[d.name] = link;
	});
});`
[/code]
links.json
[code]`
[{
"name":"link 1",
"from": "DC_Breda",
"to": "DC_Gebze",
"tooltip": "content: 'Link1'",
"strokeColor": "red"
}, {
"name":"link 2",
"from": "DC_Gebze",
"to": "DC_India_Gurgaon",
"tooltip": "content: 'Link2'",
"strokeColor": "green"
}, {
"name":"link 3",
"from": "C06-Juarez MX",
"to": "DC_India_Gurgaon",
"tooltip": "content: 'Link3'",
"strokeColor": "green"
}]`
[/code]

This way I can dynamicly update my plots and links with a cronjob. :-)
Maybe this will help someone in future!

**Comment by neveldo** [comment]
Hello @dnsBlah ,

Great, thank you for having shared this tip ! :)
