### ISSUE TITLE
Possible to use text input to highlight map areas?

### ISSUE THREAD

**Issue by alexc101** [neveldo/jQuery-Mapael#223]
Hi,

I was wondering if this could be possible? I have tried a few things, but I find I cannot update the map area from outside the function. 

I've tried to replicate adding an on: eventHandler, but I don't think it's possible to recognise an input div from inside here? Or atleast, I have had no luck.

````
on: function(e, id, mapElem) {
		$('#test').on('input', function() {
			if ($(this).val() === "true") {
				console.log("something")
			}
		});
	}
````

The aim is to insert same text as mapElem id then either select matching element or just highlight it.

(I'm not sure if this is possible, but just thought i'd ask before giving up completely).

Thanks

**Comment by neveldo** [comment]
Hello,

I don't understand clearly what you want to achieve, maybe you could explain it more, but here is a code example where an event handler (mouseover) is used in order to display some texts in an external div when the user goes over the cities : http://jsfiddle.net/neveldo/b5fj4qod/ .

**Comment by alexc101** [comment]
Hi,

I've modified a fiddle which should hopefully make things more clear - http://jsfiddle.net/uacgkx7f/

Really, I just want to be able to use an input box to be able to trigger searches for the mapElem ID's and then change their attributes according to the value entered. So for example, if I entered "department-75" then the map would update with Paris being highlighted.

I will carry on working on it using the example you linked as reference, Hopefully I will be able to progress a little further.

Thanks for the advice thus far!

**Comment by neveldo** [comment]
Hi,

Here is a quick example that does what you want : http://jsfiddle.net/neveldo/xnx7rcsf/ . Feel free to improve it for your own needs, I hope it will help you !

**Comment by alexc101** [comment]
Hi this is a big help!,

I have attempted to modify the code (please see this forked plunk: http://jsfiddle.net/alexc101/7pq01sjs/). 

I would just like to know if there is a way to reset the area back to grey if the input value no longer matches the department seen in this example?

I was hoping I could use the resetAreas to try create a new condition, like -

````
var opt = {
     resetAreas: true,
 },
if (inputVal === "delete") {
     $(".mapcontainer").trigger('update', [opt]);
     console.log("test");
}
````
or put another if statement inside the existing one with a .change parameter, but I don't this can work?

````
if (match) {
	updatedOptions.areas[inputVal] = {
		attrs: {
			fill: "#0088db"
		}
	};

	if ($(this).change(function() {
			updatedOptions.areas[inputVal] = {
				attrs: {
					fill: "#ededed"
				}
			};
			$(".mapcontainer").trigger('update', [updatedOptions, {},
				[], {
					animDuration: 1000
				}
			]);
		}));
}
````

thanks again for the help so far, hopefully I am close to my solution!

Bonne journée :)

**Comment by alexc101** [comment]
Hi,

This code works very well! I've been playing around with it recently, and I can't seem to figure out this problem (I don't think I'm too far away)! 

So all I need is for the previous element to revert back to grey once I have clicked a new list item. Here is a plnk, hopefully the problem is a little more clear once you see it.

http://plnkr.co/edit/PxN0sCEMlyo8KnXYuXbH?p=preview

and the offending code beneath;

HTML:
````
    <ul>
            <li><a href="#" class="hvr-icon-hang" id="selectCountry">France</a>
                <ul id="countries">
                    <li><a href="#" map="BE">Belgium</a></li>
                    <li><a href="#" map="FR">France</a></li>
                    <li><a href="#" map="NL">Netherlands</a></li>
                </ul>
            </li>
````
JS:
 ````
 $("ul#countries li a").click(function() {
    var updatedOptions = {
        'areas': {}
      },
      inputVal = $(this).attr("map"),
      previousSelectedMapId = null;

    if (previousSelectedMapId !== null) {
      updatedOptions.areas[previousSelectedMapId] = {
        attrs: {
          fill: grey
        }
      }
    }

    if (inputVal) {
      updatedOptions.areas[inputVal] = {
        attrs: {
          fill: green
        }
      };
      previousSelectedMapId = inputVal;
    }

    $(".mapcontainer").trigger('update', [updatedOptions, {},
      [], {
        animDuration: 1000
      }
    ]);
````

I've been trying to get it working for a few hours but I've hit a wall, I will try again later I suppose. Just wondering If there are any obvious mistakes to you?

**Comment by neveldo** [comment]
Hello @alexc101 , 

Did you found a solution to revert the color of the areas ?

**Comment by alexc101** [comment]
Hello @neveldo 

Afraid I haven't so far,  I was trying to go down the route of targeting the svg path id's, but I didn't have much luck. Have you any ideas?

**Comment by alexc101** [comment]
I've been playing around with it a little more, and thought the possibility of linking the selection to a hidden text box and using the .one handler? Unfortunately I can't get it to work, but here is a plnk if you think it could be possible this way;

http://plnkr.co/edit/4dskLo0w1XZkPckyE61z?p=info

**Comment by neveldo** [comment]
Hello @alexc101 ,

I have checked your [code sample](http://plnkr.co/edit/4dskLo0w1XZkPckyE61z?p=preview). There is just a little mistake that prevents the previous element to revert back to grey, you have to replace :

            if(previousSelectedElementId !== null) {
                updatedOptions.areas[inputVal] = {
                    attrs: {
                        fill: grey
                    }
                }

By : 

            if(previousSelectedElementId !== null) {
                updatedOptions.areas[previousSelectedElementId] = {
                    attrs: {
                        fill: grey
                    }
                }
              
Because in this case, this is the element referenced by previousSelectedElementId that you want to updated, in order to revert its background color.

**Comment by alexc101** [comment]
Hi,

Yes you are right! thanks for your time :)

Alex
