### ISSUE TITLE
Update function of version 2

### ISSUE THREAD

**Issue by emin20** [neveldo/jQuery-Mapael#224]
Hey guys,

could you may give me an example on an update function, e.g. adding a new Link in the new version ?
I basically want to delete and dynamically added link, so i just want to reset all links in a map and add a new link to the map.

Which version do i need to use to achieve that ?

Kind regards

**Comment by neveldo** [comment]
Hi @emin20 ,

I think you mean the new version 2.0.0dev that is not released yet :) In this case, all the examples are in the source, within the examples/ directory. The one you are seeking for is examples/advanced/updates_on_links_performed.html !

The version 1.1.0 of jquery mapael allows to update  links to, here is an online example for Mapael 1.1.0 : http://jsfiddle.net/neveldo/dk3ers47/

If you have a particular concern, feel free to explain it more,

Regards

**Comment by Indigo744** [comment]
Please use latest stable release 2.x
