### ISSUE TITLE
Change slice type from circle to image on mouse click?

### ISSUE THREAD

**Issue by kaityhallman** [neveldo/jQuery-Mapael#225]
Trying to add an event handler to my slices. The slice type is currently a circle with a default fill and hover attribute. Upon clicking on the circle, it should change to an image. I really have no idea how to write this out and the provided examples for click events aren't really helping, unfortunately. Any ideas?

Here is a snippet from that section of my Mapael code: 
    legend: {

                    plot: {

                        title: "Open Canvas Cities",

                        slices: [{
                            sliceValue: "Location",
                            type: "circle",
                            attrs: {
                                fill: "#8a8a8a"
                            },
                            attrsHover: {
                                fill: "#f04d00",
                                "stroke-width": 0
                            },
                            eventHandlers: {
                                click: function(e, id, mapElem, textElem, elemOptions){
                                    console.log("it works");
                                }
                            }
                        }]
                    }
                }

On click, I would like the type to change to this: 

    type: "image",

    url: "http://this-is-a-url.com/image.jpg",

    height: 40,
  
    width: 40,

Any help is SERIOUSLY appreciated. Time is of the essence.

**Comment by neveldo** [comment]
Hi @kaityhallman ,

Are you using mapael v1.1.0 (last stable release) or 2.0.0-dev ? (the code will be slightly different depending on the version you use)

By the way, it should be quite simple. Within your click event, you will need to trigger an update event that will delete the clicked circle and create an image at the same position instead (here is an example of update for mapael 1.1.0 : http://jsfiddle.net/neveldo/TKUy4/)

**Comment by neveldo** [comment]
Hello @kaityhallman , I saw you closed the issue, did you found a solution ?
