### ISSUE TITLE
title.getBBox Error

### ISSUE THREAD

**Issue by javialej87** [neveldo/jQuery-Mapael#226]
Hello Again!

I'm trying to put some legends with plots images, I'm following the example here: http://jsfiddle.net/bgjh7a4f/38/ but the error i'm getting in Chrome is the following:

jquery.mapael.js:907 Uncaught TypeError: title.getBBox is not a function

this is in Jquery.mapael:

yCenter = Math.max(yCenter, legendOptions.marginBottomTitle + title.getBBox().height + scale \* sliceAttrs[i].height/2);

What i am doing wrong?

Thanks!!

**Comment by neveldo** [comment]
Hello @javialej87 ,
Do you use jquery mapael 1.1.0 (last stable release) or 2.0.0dev ? I think that this is a bug in the 1.1.0 version that force you to set the "title" attribute within the legend options object , the version 2.0.0dev should fix this issue.

**Comment by Indigo744** [comment]
Closing as fixed
