### ISSUE TITLE
Possible to use legent as href to highlight map areas?

### ISSUE THREAD

**Issue by Dariusz-dc** [neveldo/jQuery-Mapael#227]
Hello, 
I need to do something like this: 
- Positions in the legend are link to the departments,
- after clicking on the link the department becomes highlighted. 
  Is it possible to do something like this? I will be grateful for any kind of help, because I don't know where to start, because I'm a beginner in js.

**Comment by neveldo** [comment]
Hello @Dariusz-dc , I not sure to understand what behavior you want to get with mapael ,could you explain more ? It seems that your need matches with this example : http://jsfiddle.net/neveldo/TUYHN/ where areas (departments) are linked to a legend item. When the user clicks on a legend item , it shows the related areas in a different opacity.

**Comment by Dariusz-dc** [comment]
Hi @neveldo, thank you for your replay. I want to do something like your example, but I need to link every department to a legend item separately, so the effect will be like this. The user clicks on Nord in the legend, and then the department changes color. I'll try to do as shown in the example.

**Comment by neveldo** [comment]
Indeed you can do it by creating a legend with as many slices as departments. You can use fixed values for each slice related to a department (take a look at the documentation and examples regarding fixed value slice)

**Comment by neveldo** [comment]
Indeed you can do it by creating a legend with as many slices as departments. You can use fixed values for each slice related to a department (take a look at the documentation and examples regarding fixed value slice)

**Comment by Indigo744** [comment]
@Dariusz-dc do you still need help or can we close this issue?

**Comment by Dariusz-dc** [comment]
No, all good. Thanks
