### ISSUE TITLE
Tapping plots on mobile

### ISSUE THREAD

**Issue by kaityhallman** [neveldo/jQuery-Mapael#228]
I have attached a click event to plots on mobile, where upon a tap, the plot changes from one image to another. However, it treats the first tap as whatever hover attributes are present, forcing the user to tap twice to fire the click event. Is there a way around this?

**Comment by neveldo** [comment]
Hello @kaityhallman , have you checked the native jquery touch events like touchstart/touchend (see http://stackoverflow.com/questions/4755505/how-to-recognize-touch-events-using-jquery-in-safari-for-ipad-is-it-possible) ? Or maybe jquery mobile could be an alternative as it provide a "tap" event : http://www.w3schools.com/jquerymobile/jquerymobile_events_touch.asp .

Another way to get around this may be to change your "click" event by a mouseover for mobile users ?

**Comment by Indigo744** [comment]
@kaityhallman do you still need help or can we close this issue? Thanks.
