### ISSUE TITLE
How do I change the image url on hover over the plot point?

### ISSUE THREAD

**Issue by reddo** [neveldo/jQuery-Mapael#232]
I wrote a complicated function for this, and it sort-of-works. Is there a more elegant and less hacky solution?

Here's my hack: http://jsfiddle.net/reddo/Lvxkd3fs/9/

Not that sometimes I get a console error about animDuration not being defined and sometimes the dynamically added line doesn't disappear on mouseout as it should:

```
jquery.mapael.min.js:14 
Uncaught TypeError: Cannot read property 'animDuration' of null
d.elemHover	@	jquery.mapael.min.js:14
(anonymous function)	@	jquery.mapael.min.js:14
setTimeout (async)	i	@	jquery.mapael.min.js:14
jQuery.event.dispatch	@	jquery-1.12.2.js:5226
elemData.handle	@	jquery-1.12.2.js:4878
```
![screen shot 2016-05-19 at 14 10 20](https://cloud.githubusercontent.com/assets/1180060/15391706/77c7d6b4-1dcb-11e6-9975-784c0fe98abf.png)

**Comment by neveldo** [comment]
Hello,
Is your question still relevant because it seems you have refined your code in a more straightforward way since ?

**Comment by reddo** [comment]
No, this question is not relevant anymore. Thanks for your help though.
