### ISSUE TITLE
modular maps

### ISSUE THREAD

**Issue by kockok** [neveldo/jQuery-Mapael#237]
Hello, I find loading and initializing mapael  take quite a long time. I just want "Map with links between the plotted cities", is it possible to make mapael just render the related code?

**Comment by neveldo** [comment]
Hello,

For now, Mapael can't be splitted into several components. Feel free to provide your code sample in order to check where is the performance issue.

**Comment by Indigo744** [comment]
@kockok do you have an example? What do you mean exactly by "_quite a long time_"?
Also, maybe #320 will be a first step in a more modular direction.

**Comment by Indigo744** [comment]
@kockok I would really like to know more about your use case and what you mean by "long time".

**Comment by kockok** [comment]
@Indigo744 Sorry, I no longer use this.

**Comment by Indigo744** [comment]
@kockok Still, we could try to improve a few things. If you just tell us what is "long time" and what would you accept as "reasonable time", maybe we can work on it :)
