### ISSUE TITLE
Transformation for custom SVG plot

### ISSUE THREAD

**Issue by hunterius-prime** [neveldo/jQuery-Mapael#238]
When I try to apply transformation to custom "svg" plot , i.e. "r45" , it is not working. Only after mouse hover transformation is applied and plot is moved to top/left 0/0 position and resized.

tried to recreate here http://jsfiddle.net/neveldo/z559d0s2/ , applied transform:"r45" to plot 'limoge'.

**Comment by neveldo** [comment]
Hello,

It seems that you have the same issue than @reddo : https://github.com/neveldo/jQuery-Mapael/issues/231#issuecomment-220901262. I will check it as soon as possible in order to try to find a solution.

However, it seems that your JSFidlle example don't show the issue on Limoge.

**Comment by neveldo** [comment]
Hello,

Here we go, I have upgraded the v2.0.0-dev in order to allow transformations to be applied to "SVG" plots, here is a sample : http://cdn.rawgit.com/neveldo/jQuery-Mapael/master/examples/advanced/transformations_on_svg_plots.html . I hope it will solve your issue !

**Comment by reddo** [comment]
Very cool, much obliged.

**Comment by neveldo** [comment]
You are welcome :) Feel free to give me a feedback on SVG transforms with your own project if you have the time !

**Comment by hunterius-prime** [comment]
Transformation works as intended ... for now. Thank you very much.
