### ISSUE TITLE
Update map doesn't work, and no errors are given by the browser!

### ISSUE THREAD

**Issue by samerafach** [neveldo/jQuery-Mapael#239]
Hi man, thanks a lot for the great package!

I have a problem and I'd really appreciate it if you could help me. I used the minimum example I saw here:

http://jsfiddle.net/neveldo/98xqw02n/

and I followed the pattern exactly and consulted the documentation and it didn't work. It works locally (a simpler version from the example) on my computer, but on this page:

https://budker.uni-mainz.de/gnome/gnome/plot_index_new.php

it doesn't work. This page is planned to be included in some other page. So I stripped it to minimal. It doesn't work whether included or not. The bad part is that I don't get any error messages and yet it doesn't work. It's just that nothing happens when I trigger the update. How can I debug this? Would you take a look please? I'd highly appreciate it!

**Comment by samerafach** [comment]
It turned out I was using the head version of the repository, which is not compatible with the example of 1.1.0.

**Comment by neveldo** [comment]
Hello, @samerafach , Thank you for having shared the answer !
