### ISSUE TITLE
Is it possible to add onClick handler on a legend slice ?

### ISSUE THREAD

**Issue by damthemad** [neveldo/jQuery-Mapael#243]
Hi,
i'd like to capture onClick event on a legend slice in order to display some correlated data, but unfortunately i don't succeed.

With map.defaultArea.eventHandler object youd can define handler for capture click event on areas but not on legend slice

i tried to use legend.area.slices[x].Overload.eventHandlers object in the same manner but nothing happens.

After deeply reading documentation, i can't find a way to achieve this. Is it possible ?

thanks 4 your work.

Best regards

**Comment by neveldo** [comment]
Hello @damthemad ,

You are welcome. For now, Mapael doesn't provide hooks for binding events on legend items. However, as they are just elements in the DOM, you can use a jquery selector in order to add event on them. Here is a JSFiddle example : https://jsfiddle.net/hf468nn7/ .

I hope it will help you !

**Comment by damthemad** [comment]
wow ! super speed.
Thanks a lot 4 this, it perfectly works.

i'm french also, i was in Rennes these last days, it was raining ;-)

I tried to use the Google F12 tool to indentify the objects elements to hook but it don't succeed (style 4 text element has no no class or id attribute), As i'm not a a css jedi (not a web developer in fact, not more a developper to be honnest), i tried to understand what u do, and it seems that u use a (element element selector) like this [(http://www.w3schools.com/cssref/sel_element_element.asp)] combined with an attribute selector [data-index) [https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors]

i suppose (i'll try) that i can use something like  $('.areaLegend rect[data-index]' to add a click handler 4 the legend itself (not the text, but the image)

i suppose also that with these selector the same click handler apply to all elements. I don't know how to define a selector for each legen text (just to be curious, i don't need it as the $(this).attr('data-index') syntax allow to know which item was clicked  - thanks a lot again, it was unknown 4 me).

**Comment by neveldo** [comment]
I lives in Rennes too :)  You are right regarding the rect selector, it
should work fine this way : $('.areaLegend rect[data-index]'). Maybe I
could add a specific css class to ease the selection. If you want to select
only one of the item from the legend, you can call for instance
$('.areaLegend rect[data-index=3]') (not sure about the syntax, but you can
check the doc for data selectors on joue website.

**Comment by damthemad** [comment]
thanks a lot.

**Comment by Indigo744** [comment]
Closing this, as everything seems done :)
