### ISSUE TITLE
Problems with update to 2.0

### ISSUE THREAD

**Issue by javialej87** [neveldo/jQuery-Mapael#247]
Hello!

Things have just worked great, but when i updated to version 2.0 some things behave different and other just stopped working.

This is the map i have right now 

![image](https://cloud.githubusercontent.com/assets/18535922/16530227/6f7e7b72-3f9d-11e6-8448-fcaf094cc985.png)

As you can see i have this map of Argentina with different markers on it. 

On the right i have the filters, clicking on them will light up (exclusively) those markers wich corresponds to the filter selected. 

Since i update the version some problems occured:

1) All the markers are "active" when i start the map( How can i start the map without any legend pressed, they already have the "clicked:false" attribute set).
2) Zoom in no longer works (i have an actionlistener for a click event on those markers, some of them triggers a zoom)

Example, when clicking on the grey marker:

'CABA1': {
                    type : "image",
                    url: "icon.png",
                    width: 40,
                    height: 40, 
                    opacity: 0.2,
                    longitude: -58.38952,
                    latitude:-34.51608, 
                    tooltip: {content : "C1"},
                    value: "Reg1",  
                    eventHandlers: {
                        click: function (e, id, mapElem, textElem, elemOptions) {

```
                        var offset = $(".mapcontainerArgentina").offset();
                        var map = $.fn.mapael.maps["argentina"];
                        var zoomLevel = $(".mapcontainerArgentina").data("zoomLevel");
                        var zoomRatioX = (zoomLevel * $.fn.mapael.defaultOptions.map.zoom.step) + 1;
                        var zoomRatioY = (zoomLevel * $.fn.mapael.defaultOptions.map.zoom.step) + 1;

                        var panX = $(".mapcontainerArgentina").data("panX");
                        var panY = $(".mapcontainerArgentina").data("panY");

                        var ratioX = map.width / $(".mapcontainerArgentina").width();
                        var ratioY = map.height / $(".mapcontainerArgentina").height();

                        // Get (x, y) mouse coordinate
                        var x = (e.pageX - offset.left);
                        var y = (e.pageY - offset.top);
                        // Convert to (x, y) map coordinate
                        var xMap = x * ratioX;
                        var yMap = y * ratioY;
                        // Take into account zoom
                        var xMap = xMap / zoomRatioX;
                        var yMap = yMap / zoomRatioY;
                        // Take into account panning
                        var xMap = xMap + panX;
                        var yMap = yMap + panY;
                        // Now we have (x, y) in map coordinate
                        console.log(xMap, yMap);

                        // Zoom to this position
                        if($('[data-id="' + id + '"]').css('opacity') == 1){
                            $(".mapcontainerArgentina").trigger('zoom', {level : zoomLevel + 5, x:xMap, y:yMap});
                            $(".mapcontainerArgentina").fadeOut();
                            $(".mapcontainerMETRO").fadeIn();                               
                            if ($(".mapcontainerMETRO .plotLegend text:eq(" + RegionSelected + ")").css('opacity') < 1)
                                $(".mapcontainerMETRO .plotLegend text:eq(" + RegionSelected + ")").trigger('click');

                        }

                    }
                }
            }
```

it fails here:
$.fn.mapael.defaultOptions.map.zoom.step

the error is **"Uncaught TypeError: Cannot read property 'map' of undefined"**

Thanks!

**Comment by dnsBlah** [comment]
I have the same issue, as I normally used :
$.fn.mapael.defaultOptions.map.defaultArea.attrsHover = {};
to disable hover attributes, it now says, $.fn.mapael.defaultOptions is undefined. :-)

**Comment by neveldo** [comment]
Hello,

Indeed, there are some non-backward compatible changes from 1.1.0 to 2.0.0. Most of them are listed here : https://github.com/neveldo/jQuery-Mapael/blob/master/UPGRADE.md .

@javialej87 : could you provide a complete JSFiddle sample of your code in order to fix it for 2.0.0 ?

@dnsBlah : regarding the default options, you can now use: $.mapael.prototype.defaultOptions as explained in the upgrade.md file, it should work fine !

**Comment by Indigo744** [comment]
@javialej87 & @dnsBlah do you still need help or is everything ok?

**Comment by dnsBlah** [comment]
@Indigo744, I’m sorry I think it was solved yes, but due requirements and other implementations I moved over to leaf of vis? I’m not sure its a while ago.
I do like the project for sure !!
