### ISSUE TITLE
jQuery2 compatible release

### ISSUE THREAD

**Issue by Telem** [neveldo/jQuery-Mapael#252]
Hello,

I would like to benefit from the enhancements released in v2.0.0 (more specifically the mem-leak fix), but I can't migrate my project to jQuery3.
I would prefer to keep using official releases through bower rather than fork from 1.1.0, so would it be possible to get a 1.2.0 release from before the move to jQuery3 ?
Or alternatively, do you know of a simple way to bootstrap mapael with jQuery3 while keeping jQuery2 global (in a browser environment) ?

Thanks

**Comment by neveldo** [comment]
Hello,

For your information, Mapael 2.0.0 works fine with jQuery 2 too, so you should be able to keep your current version of jQuery and use Mapael 2 !

Feel free to give me a feedback,

**Comment by Indigo744** [comment]
@Telem can we close this?

**Comment by Telem** [comment]
absolutely, sorry I didn't close this sooner.
