### ISSUE TITLE
Map with full width and full height

### ISSUE THREAD

**Issue by cat-labs** [neveldo/jQuery-Mapael#254]
Hi there,

First thank you for the really nice plugin!

I am trying to create a map which take 100% width and 100% height of the browser. The idea would be to keep the ratio of the map, if for instance the height is big, then the width of the map will be larger than the window size and we can navigate through paning.
I have set the width of the map larger than the window size but the problem is that I can't pan to the zone which is overflowing the screen.

here is the page http://ivsimpact.org/preview (reduce the width of your browser, then refresh)

Any idea on how to achieve this?

**Comment by neveldo** [comment]
Hello @cat-labs , 

I think you should find useful information in this thread : https://github.com/neveldo/jQuery-Mapael/issues/76 in which the map have to fit with the window height.

Feel free to give us a feedback with your map !

**Comment by cat-labs** [comment]
Hi,

Didn't see this thread, it should make it, I ll try it later :-)
