### ISSUE TITLE
getCoords function (Mercator projection)

### ISSUE THREAD

**Issue by SafaaFX** [neveldo/jQuery-Mapael#255]
Hello, first of all thank you so much for this amazing plugin, I'm using it on my project. in the first version of the project I used just the map world_countries and everything was good. Now I'm preparing  a new version where I want to add the subcontinents maps.

I managed to add the maps from svg files, but the problem is the getcoords function. I'm using a mercator projection so,I tried this algorithm here: https://github.com/Indigo744/jQuery-Mapael/blob/e1657c047fbab109591ec80aa880d61ccfcbf411/js/maps/world_countries_mercator.js

for all the other maps I just changed the leftLongitude, rightLongitude, topLatitude, bottomLatitude. but I don't get the plots in their right places!!

I don't know if what I did is right??? any advices please..

Thank you so much,

Safaa.

**Comment by neveldo** [comment]
Hello @SafaaFX ,

You did it right, it should work with the proper values for  leftLongitude, rightLongitude, topLatitude, bottomLatitude.

Are you sure your map is a mercator projection ? (Did you try the algorithm from the miller' one : https://github.com/neveldo/jQuery-Mapael/blob/master/js/maps/world_countries_miller.js just in case ?)

Could you provide a JSFiddle with your map in order to check what could be wrong ?

**Comment by SafaaFX** [comment]
Hello @neveldo 

I just used the miller algo it worked for just some places :/

I had never made a jsfiddle, See if this can help :  https://jsfiddle.net/1ts7h4e7/3/

here how the map looks like:

![etranger](https://cloud.githubusercontent.com/assets/7228195/17968101/4cc84aa0-6acb-11e6-90cc-d741f5faf79a.PNG)

**Comment by SafaaFX** [comment]
might the problem be related to the height and width that are variables ??

**Comment by neveldo** [comment]
Hello,

What is the source of your map ? I have checked it, and it seems not to be a Mercator projector, nor a miller or equirectangular one.

**Comment by SafaaFX** [comment]
Hello @neveldo
Yes you're right. It was our designer who made it I unfortunately don't know from which reference he get it. But for now we found another solution, its to provide directly the x and y coordinates using js and the cursor position...

**Comment by SafaaFX** [comment]
By the way thank you so much for this amazing plugin. I will let you know once I'm finished to check out the project :D

**Comment by neveldo** [comment]
You are welcome, I'm glad you appreciate Mapael ! I look forward to discover your project :)

**Comment by ravivermas** [comment]
Hi Neveldo,

I am new to Mapael and I have used this plugin to convert my own svg map to mapael. But I am facing challenge with getCoords function and I am not able to plot markers with the longitude and latitude which I have for cities on map.

Can you please help me on this @neveldo

**Comment by neveldo** [comment]
Hello @ravivermas ,

I would be glad to help you, but could you please open a new issue instead of answering on a closed one ? (you can take the opportunity to add some info as your map at its current state (or the SVG), and the projection used).
