### ISSUE TITLE
Shrink plots when zoomed in all the way

### ISSUE THREAD

**Issue by kennethpb** [neveldo/jQuery-Mapael#256]
When the map is zoomed in all the way, there are plots that overlap which makes them almost inaccessible. Is there a way to shrink the plots when zoomed in all the way? Please advise. Thank you! Example: https://storage.googleapis.com/cf-pathways-assets/interactive_map/pathways_map.html

Kenny

**Comment by neveldo** [comment]
Helloo @kennethpb ,

I answered here : #253 Give me a feedback :). I think I will bring this feature in the next release.  (feel free to contribute if you have time !).

**Comment by kennethpb** [comment]
Hi @nveldo! Thanks for your help as I try to wrap my head around this issue. I am looking at your jsfiddle solution: http://jsfiddle.net/neveldo/ebxnu6b8/

Does this require to change the jquery.mapael.js file? If not, which file do I need to modify?

Please advise.

Kenny

**Comment by neveldo** [comment]
Hi,

This is an updated example compatible with jQuery 2.0.0 , you don't have to change the jquery.mapael.js file if you are already using the latest version. All you need is to add the following event listener : `$(".maparea5").on("zoom.mapael", function() {}` and adapt it to your code. By the way, this is far from the perfect solution as the render is very slow.

You can take a look at this thread : https://github.com/neveldo/jQuery-Mapael/issues/253 where we discuss the same issue.

**Comment by Indigo744** [comment]
Discussion will continue on #253
