### ISSUE TITLE
Is it possible to change the width without change the height together

### ISSUE THREAD

**Issue by TrendAlan** [neveldo/jQuery-Mapael#258]
First, thanks for your amazing plugin. I am using this in my project.
My problem is that the width container of the map maybe change but the height is fixed.
So I may want to change the width only without change the height together.
I try to change self.paper.setSize(containerWidth, self.mapConf.height \* newScale); to 
self.paper.setSize(containerWidth, self.mapConf.height);
But this will bring some other problems, such as when zoom in to some country, the position is incorroct.
I am using world_countries.js and the default height is 1000 and the width is 400.
Hope you can help me on this.
Thank you so much.

**Comment by TrendAlan** [comment]
Thanks for your patient answer.
It works well with afterInit function and the with and height is what I want.
But when zoom with scrollbar or the zoom button, the map will change back to the original size.
Could you help to make a demo with zoom function in JSfiddle?
Thank you very much.

**Comment by neveldo** [comment]
Hello,

You ae welcome. Unfortunately, this is a normal behavior of the zoom feature, as the viewbox of the SVG map is re-computed at each zoom action, in a way that preserve the aspect ratio ... I think you should override the events binded related to the zoom feature in order to get your custom behavior !

**Comment by TrendAlan** [comment]
Thanks for your answer. 
It's may take much effort to do what I want.
I will just keep the aspect ratio, just as the other maps do, such as highmap.
