### ISSUE TITLE
Jquery easing

### ISSUE THREAD

**Issue by cat-labs** [neveldo/jQuery-Mapael#261]
Hi,

I would like to know what's the best way to integrate jquery easing functionalities when zooming into the map. I think the linear easing it's not the best but a easeOutQuad for instance might work better.

Any suggestions?

**Comment by tammo0** [comment]
As far as i know the easing works with RaphaelJS.
Take a look at line 51-53 at my jsfiddle: https://jsfiddle.net/t36y5mh3/
The RaphaelJS reference can be found here: http://dmitrybaranovskiy.github.io/raphael/reference.html#Raphael.easing_formulas

**Comment by cat-labs** [comment]
Allright, didn't notice this parameter, great!

**Comment by cat-labs** [comment]
In fact it works ok with a mouse but with a trackpad, at least on mac it is not smooth at all. It waits like half a second before it zoom.

**Comment by tammo0** [comment]
Yep, i got the same issue even with mousewheel. Perhaps its a performance problem on maps with lots of plots?

**Comment by cat-labs** [comment]
Well , for instance no plots on the map I am using and also on the fiddle you gave me:
https://jsfiddle.net/t36y5mh3/
Only 2 plots and same issue

**Comment by tammo0** [comment]
for me its much smoother with a higher step-value like 1.25: (line 49)
https://jsfiddle.net/t36y5mh3/1/

**Comment by tammo0** [comment]
i think i'll use step: 1.25, animDuration: 1000 and ease-in-out. at least feels a bit smoother: https://jsfiddle.net/t36y5mh3/4/

**Comment by cat-labs** [comment]
yeah you're right :-)

Thanks dude!

**Comment by neveldo** [comment]
Hi,

You are right, zooming into SVG is a little costly for the browser, so it can be slow with low configurations or mobile devices. I didn't found a fix for now, but feel free to contribute if you can !

**Comment by Indigo744** [comment]
The zoom functionality might need some rework indeed.

For instance, instead of `setInterval` to animate the viewPort, maybe use `requestAnimationFrame` where possible (recent browsers).

**Comment by Indigo744** [comment]
@cat-labs @tammo0 can you check on the new Zoom algorithm? See linked PR.
