### ISSUE TITLE
always a missing map

### ISSUE THREAD

**Issue by mroswell** [neveldo/jQuery-Mapael#262]
I have been adjusting things for a long time, and have not determined what is causing a map to not display on the page. At first I thought it won't display more than two maps. So I added a test map, and the test displays. Then I thought: whatever is the third map doesn't display. But the issue seems more complicated than that. Why won't #relayfoods display?

https://mroswell.github.io/mapael-maps/examples/basic/ingredient-delivery-services.html

https://github.com/mroswell/mapael-maps/blob/gh-pages/examples/basic/ingredient-delivery-services.html

I've had similar issues when trying to move the legend to the top of the page. (where it just shows the "alternate" text.

Is the advanced multiple_instances relevant here? (BTW, when I view that on the website, I see multiple maps, but in my own browser I don't, but that's probably a separate issue. Well, when I  changed to the min version, it fixed multiple_instances (so I see all four maps on that page) but on my page, above, even with shift to .min version, I still only see three including the text map.

BTW, apart from this issue, really appreciating Mapael. I hope I can get it to work for my project.  Can anyone identify why  #relayfoods map will not display ? 

Margie

**Comment by mroswell** [comment]
Apparently, if any of the mapcontainers are missing this:
```
    <div class="areaLegend">
      <span>Alternative content for the legend</span>
    </div>
```
One of the maps will disappear. This seems awfully strange. For instance, if the areaLegend was missing from the first item, the last map might not appear. Odd, but I've seen that you can set a custom legend. Is there a way to set it to empty, so that I don't have the same legend appearing on every map?

**Comment by mroswell** [comment]
If  I remove the legendArea markup for a given mapcontainer, a map (and not usually the one I removed the markup for) will disappear. But if I do style="display:none" on that div, I can keep the markup and all the maps will still display.

I'm not sure what area of the code insists that the mapcontainer have a legend, but that's what I found, in any case.

**Comment by neveldo** [comment]
Hello @mroswell , I'm glad you appreciate Mapael,  thanks for reporting this issue.

It seems that you have solved the issue in your code sample : https://mroswell.github.io/mapael-maps/examples/basic/ingredient-delivery-services.html . Could you upload a code sample where the iissue appear in order to check if there is a bug into Mapael ?

**Comment by Indigo744** [comment]
@mroswell any update on this?
