### ISSUE TITLE
Delete all plots and areas in Mapael 1.x

### ISSUE THREAD

**Issue by nlemsieh** [neveldo/jQuery-Mapael#264]
Hi,
As I noticed Mapael v2.x supports deleting all plots and areas . So, I would like to do the same but using the version 1.x. is it possible ?

**Comment by neveldo** [comment]
Hello @nlemoine ,

Take a look at the documentation for the v1.x : https://rawgit.com/neveldo/mapael-documentation/2658ed08d6bf4bec367e13f3a0715853b07b8230/index.html#update-map-data . You can trigger an 'update' event with an array of plots to delete as argument. You just have to build an array with all your plots if you want to delete them all.

**Comment by nlemsieh** [comment]
Thanks @neveldo
