### ISSUE TITLE
change color plot

### ISSUE THREAD

**Issue by DK-Webentwicklung** [neveldo/jQuery-Mapael#266]
Hi, is it possible to change the color of a plot? I would use this version: "links_between_plotted_cities.html" and want to change the blue pots and lines to orange.

Thanks for support.
David

**Comment by neveldo** [comment]
Hello,

Of course you can change the color of a plot, this is one of the basic features of Mapael. Feel free to take a look at the samples within the sources and in [the documentation](http://www.vincentbroute.fr/mapael/) to get more information.

**Comment by Patrick1909** [comment]
The color should be changed with the parameter 

`fill: #000000`

**Comment by Indigo744** [comment]
Closing this issue. Feel free to reopen if you need more help.
