### ISSUE TITLE
start animation #2 after previous animation is finished

### ISSUE THREAD

**Issue by Patrick1909** [neveldo/jQuery-Mapael#271]
Hello,

I want to start the second anaimation (creating link2) just after the first one is finished.

With this code both are starting at the same time :-(

I don't found an animDuration, but no animStart variable or something simuliar.

`afterInit : function($self, paper, areas, plots, options) {
                           var newLinks = {
                                 "link1": {
                                         between: ['berlin', 'istanbul']
                                 }
                           }
                           $(".mapcontainer").trigger('update', [{
                                 newLinks: newLinks,
                                 animDuration: 1000
                           }]);

                           //  start after link1 is finished
                           var newLinks = {
                                 "link2": {
                                         factor: -0.3,
                                         between: ['istanbul', 'tiflis'],
                                         attrs: {
                                                 "stroke-width": 1,
                                                 "stroke-linecap": "round"
                                         }
                                 }
                           }
                           $(".mapcontainer").trigger('update', [{
                                 newLinks: newLinks,
                                 animDuration: 1000
                           }]);
                    }`

Could anybody help?

pib3k

**Comment by neveldo** [comment]
Hi @Patrick1909 ,

There is an ['afterUpdate' option](http://www.vincentbroute.fr/mapael/#update-map-data) for the 'update' event that could be used to draw the second link. However, I think this option is not fully implemented, indeed I think it will not wait the first "update" to run.

Another way that should do the trick is to call setTimeout() with a timeout value that is equal to the first update duration :

```

setTimeout(
    function() {
         //  start after link1 is finished
         var newLinks = {
               "link2": {
                       factor: -0.3,
                       between: ['istanbul', 'tiflis'],
                       attrs: {
                               "stroke-width": 1,
                               "stroke-linecap": "round"
                       }
               }
         }
         $(".mapcontainer").trigger('update', [{
               newLinks: newLinks,
               animDuration: 1000
         }]);
    },
    1000
);
```

**Comment by Patrick1909** [comment]
Thank you very much for your support. The setTimeout function works pretty well.
