### ISSUE TITLE
Rotate plot image 

### ISSUE THREAD

**Issue by Patrick1909** [neveldo/jQuery-Mapael#272]
Hello, 

does anybody know how I can change the slope of an image? I want to rotate the image e.g. 45 degrees like this: transform: rotate(45deg);

Is it possible to change the slope directly here?:
`plots: {
                    'paris': {
                        type: "image",
                        url: "img/dark/appbar.plane.png",
                        width: 38,
                        height: 38,
                        latitude: 48.86,
                        longitude: 2.3444,
                        attrs: {
                            opacity: 1
                        },
                        attrsHover: {
                            transform: "s1.5"
                        }
                    },`

Thank you very much for any support.

**Comment by Patrick1909** [comment]
I guess the easiest solution is transform: "r45":

`plots: {
                    'paris': {
                        type: "image",
                        url: "img/dark/appbar.plane.png",
                        width: 38,
                        height: 38,
                        latitude: 48.86,
                        longitude: 2.3444,
                        attrs: {
                            opacity: 1,
                            transform: "r45"
                        },
                        attrsHover: {
                            transform: "s1.5"
                        }
                    }
}`

**Comment by neveldo** [comment]
Hello @Patrick1909 ,

You are right, the transform r45 is the way to go for your need, thank for having kept updated !
