### ISSUE TITLE
Bug move map on Firefox

### ISSUE THREAD

**Issue by aliocza** [neveldo/jQuery-Mapael#277]
Hi,

On Firefox 50.0, if you click on area and after you again click on the same area to move the map, you have the area in picture instead of moving the map.
example with colorado :
![bug](https://cloud.githubusercontent.com/assets/8338334/20563747/326f5b70-b18a-11e6-96ac-42384721d65b.jpg)

**Comment by neveldo** [comment]
Hello @aliocza ,

Thank you for having reported this bug. However, I'm not able to reproduce it with Firefox 50.0 and Mapael 2.0.0 on the demo 'basic/legend_slices_fixed_values.html' which seems to be the same as your screenshot. Which version of mapael are you using ? 

What do you mean by "moving the map" ?

**Comment by aliocza** [comment]
you can't move the map in 'basic/legend_slices_fixed_values.html' because the zoom is disabled but we can reproduce de bug without zoom.
For reproduce bug, stay on any countries and wait ending animation background color and try drag as if you want to move in the map. 
Demo for moving in the map after zoomed : 
![optimised](https://cloud.githubusercontent.com/assets/8338334/21140874/8cbb28ec-c13a-11e6-9711-7d09fe090cc6.gif)

**Comment by neveldo** [comment]
Hello @aliocza ,

I have just published a fix in the master branc for this issue : https://github.com/neveldo/jQuery-Mapael/commit/c4efaae922fb901b4f5180b3e6d7fc212939665d . Could tell me if it's ok for you now ?

**Comment by aliocza** [comment]
Its works. thank you :)
