### ISSUE TITLE
Plot not clickable (for deselection)

### ISSUE THREAD

**Issue by cmssec** [neveldo/jQuery-Mapael#278]
Hello,

I'm creating a country selector (can select multiple countries, travel site). Basically it shows world map, and allows people to click on each individual countries.. and on each click data goes to the server to record the clicked country.

This works, on click.. i send data to SQL server, it gets recorded, and when I open the page again.. i have previously selected areas, plotted (it's type SVG, colors the whole country.. using path).

The problem is, I cannot click on the area again. If i click on the area after refreshing the page (after it gets plotted), nothing happens.. the onClick event is not firing when I click on a country that has been plotted. I need to be able to click on a plotted country to 'deselect' it .. (send ajax request to server to remove the specific country from visited countries). Here's my JS code so far:

`$(function () {
    // Show loading message
    var plotg;
    
    // We need a setTimeout (~200ms) in order to allow the UI to be refreshed for the message to be shown
    setTimeout(function(){
        var plott;
        // Get the data
        $.getJSON("actions/profile.php?action=countries_visited&get=1", function (data) {
        // Success
        // This variable will hold all the plots of our map
        var plots = {};
        var plotsColors = chroma.scale("Blues");
        // Parse each elements
        $.each(data, function (id, elem) {
            // Check if we have the GPS position of the element
            if (elem.fields.wgs_84) {
                // Will hold the plot information
                var plot = {};
                // Assign position
                plot.path = elem.fields.path;
                plot.type = elem.fields.type;
                // Assign some information inside the tooltip
                plot.tooltip = {
                    content: elem.fields.text
                };
                // Assign the background color randomize from a scale
                plot.attrs = {
                    fill: '#00a4ff',
                    opacity: 1
                };
                // Set plot element to array
                plots[id] = plot;
                this.plotg = plots;
                plott = plots;
                //console.log("Plots assigned: " + JSON.stringify(this.plotg));
            } else {
                console.warn("Ignored element " + id + " without GPS position");
            }
        });

        // Create map
        var test_plots = {
                // SVG plot
                'Limoge': {
                    type: "svg",
                    path: "M559.521,292.237l-1.454,-0.289l-0.871,0.289l-1.163,-0.581l-1.163,0.000l-1.745,-1.162l-2.326,-0.579l-0.580,-1.744l0.000,-0.870l-1.455,-0.292l-2.907,-2.903l-0.870,-1.742l-0.582,-0.580l-1.163,-2.034l3.197,0.291l0.872,0.291l0.872,0.000l1.454,-1.744l2.616,-2.322l0.872,-0.291l0.291,-0.871l1.744,-1.162l2.036,-0.289l0.000,0.870l2.325,0.000l1.452,0.581l0.582,0.582l1.163,0.289l1.452,0.871l0.000,3.486l-0.582,2.032l0.000,2.033l0.293,0.870l-0.293,1.452l-0.289,0.290l-0.874,2.033l2.904,-3.195z",
                    width: 30,
                    height: 30,
                    attrs: {
                        opacity: 1
                    },
                    tooltip: {
                        content: "aaaaaaaa"
                    }
                },
                
                // SVG plot
                'Test1': {
                    type: "svg",
                    path: "M506.906,166.5l-9.592,5.226l-7.849,5.227l-4.070,1.453l-2.906,0.000l0.000,-1.742l-1.452,-0.291l-1.454,-0.872l-0.873,-1.161l-9.301,-6.098l-9.301,-6.098l-10.176,-6.679l0.000,-0.291l0.000,-0.290l0.000,-3.194l4.361,-2.032l2.906,-0.581l2.036,-0.581l1.162,-1.452l3.197,-1.162l0.000,-2.032l1.744,-0.291l1.162,-0.870l3.782,-0.582l0.289,-0.871l-0.582,-0.580l-0.871,-2.905l-0.291,-1.742l-1.163,-1.742l2.907,-1.452l2.907,-0.581l1.744,-1.161l2.617,-0.872l4.650,-0.289l4.651,-0.291l1.162,0.291l2.615,-1.162l2.911,0.000l1.160,0.871l2.035,-0.290l-0.581,1.451l0.290,2.614l-0.579,2.323l-1.745,1.451l0.290,2.034l2.325,1.742l0.000,0.581l1.745,1.162l1.163,4.936l0.871,2.322l0.000,1.453l-0.291,2.033l0.000,1.451l-0.291,1.452l0.291,1.743l-1.162,1.161l1.744,2.033l0.000,1.162l1.163,1.451l1.163,-0.580l2.035,1.451l-1.452,-1.743z",
                    attrs: {
                        opacity: 1
                    },
                    tooltip: {
                        content: "sad"
                    }
                }
            };
           
        var countryToggled = [];
                        
        $(".mapcont").mapael({
            
            map : {
                name : "world_countries",
                defaultPlot: {
                    attrs: {
                        fill: "#004a9b", opacity: 0.6
                    },
                    attrsHover: { 
                        opacity: 1
                    },
                    text: {
                        attrs: {
                            fill: "#505444"
                        },
                        attrsHover: {   
                            fill: "#000"
                        }
                    }
                },   
                defaultArea: {
                    attrs: {  
                    fill: "#f4f4e8", stroke: "#ced8d0"
                },
                attrsHover: {
                    fill: "#a4e100"
                },
                text: {
                    attrs: {
                        fill: "#505444"
                    },
                    attrsHover: {
                        fill: "#000",
                        text: 'text' 
                    }
                },   
                eventHandlers: {
                    click: function (e, id, mapElem, textElem) {                        
                        if (jQuery.inArray(id, countryToggled) == -1) {
                            // Add to array
                            console.log("adding.." + id);
                            countryToggled.push(id);
                        } else {
                            for(var i = countryToggled.length; i--;) {
                                if(countryToggled[i] === id) {
                                    countryToggled.splice(i, 1);
                                }
                            }
                            console.log("removing.." + id);
                        }
                         
                        // Send the array to server
                        $.ajax({
                            type: 'POST',
                            url: '/profile.php?action=countries_visited',
                            data: {countryToggled},
                            success: function (data) {
                                var obj = JSON.parse(data);
                                
                                if (obj.status == true)
                                {   
                                    $.floatingMessage("Added " + id + " as visited",{
                                        time:1500,
                                        position : "bottom-right"
                                    });
                                       
                                    console.log("Traveled: " + obj.message);
                                    
                                }   
                                    
                            },      
                            complete: function (data) {
                                // Schedule the next   
                            }
                        });  
                             
                        var newData = {
                            'areas': {}
                        };
                        
                        if (mapElem.originalAttrs.fill == "#f4f4e8") {
                            newData.areas[id] = {
                                attrs: {
                                    fill: "#5ba4ff"
                                }
                            };
                            console.log("selecting");
                        } else {
                            newData.areas[id] = {
                                attrs: {
                                    fill: "#f4f4e8"
                                }
                            };
                            console.log("deselecting"); 
                        }
                        $(".mapcont").trigger('update', [{mapOptions: newData}]);
                    }
                }
            }
        },
        plots: plots
    });
        
});}, 300);});
// json // settimeout, function`

Thanks

**Comment by neveldo** [comment]
This is strange, there is no reason for the event to be fired in one case and not in the other as you only change some properties of the paths when they are retrieved from your API. 

Could you provide a full sample on JSFiddle that highlight your issue ? I have tried your code, but I have some undefined vars, and I can't test the click action as it fire calls to your API.

**Comment by cmssec** [comment]
https://jsfiddle.net/uh0rLam7/2/
Sorry, the code is not cleanest..

Try clicking on a blue ("selected" or .. "plotted") area.
It's not firing click event... nothing is happening when you click on it.

So I have a list of selected countries, and what I want is for user when he loads his page.. he can actually deselect the selected countries, as well as add them. For now only adding new ones work, cannot remove the selected countries as the click event is not firing.
It's a "choose countries you visited" world map.. for user to select countries via map, not enter them via select or whatever.

I can't find example that does this "deselection" of plotted area.

**Comment by neveldo** [comment]
Ok I see what is wrong : 

First, the eventHandlers must be defined in the map.defaultArea (or map.defaultPlot) section, such as in [this example](https://rawgit.com/neveldo/jQuery-Mapael/2.0.0/examples/advanced/eventHandlers_option_and_update_event_refresh_onclick.html). In your code, eventHandlers is defined directly in the map section. 

Moreover, in your callback function, the first line is a return statement, so the rest of the function will never be executed.

Eventually, you are using in a wrong way the "plot" option. The plot option is not aimed to superimpose the areas for updating the background-color, there are dedicated options to do that. I think you should take a look at the code samples available here : http://www.vincentbroute.fr/mapael/ in order to take advantage of all the options.

**Comment by Indigo744** [comment]
@cmssec do you still need help or can we close this issue?
