### ISSUE TITLE
Changing the fill colors of areas of the map based on values from array

### ISSUE THREAD

**Issue by nnekaen** [neveldo/jQuery-Mapael#279]
Hi
 I am currently in the process of extending the functionality of my Mapael map to take values of an array and change the color based on if the value is a “Member” or “Non Member”. The array i created is defined as follows :

`countries={"Afghanistan":"Non Member", "Albania":"Member", "Algeria":"Member",and so on.}`

1.	My first question is, is it possible to change the field colors depending of variables of an array ?. I managed to display the values of the above array in the function:
```

                var getElemID = function(elem) {
                // Show element ID      
                return $(elem.node).attr("data-id")+":" + countries[$(elem.node).attr("data-id")]; //
                     
                                                                               };
```

Here are the other codes:

```
var getElemcolor= function(attrs) {
  
    if (countries[$(elem.node).attr("data-id")]=="Member")
                 {
                return attrs= 'blue';
                    
                 }
    else         
                         {return attrs= 'red';}
                   
                }
         
         
                    
     
                  
            $(".mapcontainer_un").mapael({
                map: {
                    name: "world_countries_un",
                    zoom: {
                        enabled: true,
                        maxLevel: 15
                    },  
                     
                    
                     defaultArea: {
                        attrs: {
                        	fill: getElemcolor, // my function for color i want to define
                        	stroke: "#5d5d5d",
                        	"stroke-width": 0.2,
                        	"stroke-linejoin": "round"
                    	},
                    	attrsHover: {
                        	fill: "#E98300",
                        	animDuration: 300
                    	},
                          tooltip: {
                            content: getElemID
                        }
                    },
                   
                    defaultPlot: {
                        size: 9
                    }
                },
                
```
                

2.	Secondly, Is it possible to use a function in the fill attributes, for instance   attrs: {fill: myfunction} ?, If so what is the correct syntax for this?

I would be so grateful for your help

Thanks very much

**Comment by neveldo** [comment]
Hello,

For now, it's not possible to use a function in the fill attributes, but I think it may be an interesting improvement.

However, have you checked the mapael sample ["Map with a legend where slices are specified with a fixed value instead of min and max values"](https://rawgit.com/neveldo/jQuery-Mapael/2.0.0/examples/basic/legend_slices_fixed_values.html). As you can see, mapael already allows you to set fixed values in the legend configuration. You can easily adapt it to your needs in order to set a color for member countries and another color for non-member ones.

**Comment by nnekaen** [comment]
Ok. Great. Thanks!!

**Comment by neveldo** [comment]
I'm glad it helped you!
