### ISSUE TITLE
Problème utilisateur outil conversion

### ISSUE THREAD

**Issue by laurentbreizhnet** [neveldo/jQuery-Mapael#284]
Bonjour,

Tout d'abord, merci pour le travail réalisé autour de mapael.
Je souhaiterais créer une map personnalisée avec des valeurs issues d'une base de données pour les éléments path.d et path.data-id 
A titre d'exemple, j'ai recréé via illustrator une map vertorielle ( tout ressemblance avec notre bonne terre est involontaire :) ) et j'ai donc utilisé votre outil de conversion .svg => .js pour obtenir le fichier joint.
[map.txt](https://github.com/neveldo/jQuery-Mapael/files/679618/map.txt).

Je souhaiterais donc générer la partie :
`<elems>
<data-id> : <d>
<data-id> : <d>
</elems>`

Est ce possible et comment puis je procéder ? 
Quel fonction/méthode puis-je utiliser ?
Merci d'avance.

**Comment by neveldo** [comment]
Bonjour,

Je ne comprends pas bien ce que vous voulez générer ? A quoi correspond cette partie : 

`<elems>
<data-id> : <d>
<data-id> : <d>
</elems>`

?

Votre carte du monde (map.txt) devrait être utilisable dans mapael sans étape supplémentaire à priori. Il suffit de charger mapael, votre carte JS, et d'instancier une map sur la div de votre choix.

**Comment by Indigo744** [comment]
@laurentbreizhnet où en êtes vous ? Vous avez toujours besoin d'aide?
