### ISSUE TITLE
Unable to set circle fill attribute of url path element

### ISSUE THREAD

**Issue by lingfei87** [neveldo/jQuery-Mapael#285]
Hello, I want to set the circle fill color to gradual change。

For example: 
\<s v g width="240" height="240" style="background-color: #000;"\>
			\<defs\>
			\<radialGradient id="Gradient"\>
				\<stop offset="0%" stop-color="#fff" stop-opacity="0"\ />
				\<stop offset="100%" stop-color="red" stop-opacity="0.9"\ />
			\</radialGradient\>
			\</defs\>
\</s v g\>			
			\<circle cx="100" cy="50" r="40" fill="_**url****(#Gradient)**_" \/>

When i set defaultPlot attrs fill to _url(#Gradient)_  not the concrete color like "#f00" after refreshing my web browser, the url parameter #Gradient is translated to GUID similarly. Is there some processing for url method rewrite in Mapael.js? I cann't find the  definition of url method .What should i do ? 
Thank you very much! 
Wishing your reply!

**Comment by neveldo** [comment]
Hello @lingfei87 ,

Have you checked the Raphael.js documentation regarding gradients for the 'fill' attribute ? Take a look at the [Elements.attr -> Gradients part](http://dmitrybaranovskiy.github.io/raphael/reference.html#Element.attr), there are several ways to define gradients through the 'fill' attribute.

**Comment by Indigo744** [comment]
@lingfei87 do you still need help or can we close this issue?
