### ISSUE TITLE
jquery-mousewheel event version 2.0.0

### ISSUE THREAD

**Issue by AugustinMortier** [neveldo/jQuery-Mapael#287]
With the version 2.0.0, I cannot access anymore to the jquery-mousewheel events:

`$('.mapcontainer').bind("mousewheel", function(e) {
    console.info('zoom event')
}`

This command was working on the 1.1.0 version.

**Comment by neveldo** [comment]
Hello @AugustinMortier , thanks for reporting this issue, I will check it asap !

**Comment by neveldo** [comment]
Hello @AugustinMortier , it should now be fixed since this commit : https://github.com/neveldo/jQuery-Mapael/commit/ff74f9b4961d3af1513c7d7f689b36ca60751dd9 . It will be available in the next version that will be released soon.
