### ISSUE TITLE
Mapael/Raphael - plots and areas controlled by a single legend item

### ISSUE THREAD

**Issue by arniesaha** [neveldo/jQuery-Mapael#29]
I've been working on few custom SVG maps based on Raphael.js but Mapael is the library that I'm working with. I have setup a jsfiddle of the example to be better explain my.

http://jsfiddle.net/arnabsaha/3jNE9/

As you can see, I have mapped the different paths to show tooltips of different descriptions. Along with plots for things like stairs/escalators (in a mall environment) with it's legend there is another legend for the different sections/paths of the map.

Now what I need to do is find a way where for eg. click on the legend item to hide/show a path/area of the map (which is achieved) along with the tooltip description that is shown when hovered on that particular path/area.

Now, after trying few unsuccessful things, I was thinking of a workaround where clicking on the legend item for the path/area to also hide/show a plot with a text description attribute. For eg. In the fsfiddle example, click on 'Azul by moussy', (first item in the areas legend) the area is highlighted, along with this, if I could also hide/show a plot (with text attribute) which is the description for that particular path/area?

I tried another workaround which involves another pop up library http://dimsemenov.com/plugins/magnific-popup/documentation.html where I'm trying to show a related popup with the tooltip styling at a fixed position relevant to the area that I click on the legend.

eg http://startupmedia.net/clients/new_maps/L4/

But, here the issue is since I'm unable to add an id to a single text item of the legend, the pop will show for all the legend items including the plot menu and the area menu. In this case, is there a way I can have a id for a single legend menu item. In that case I can call the popup function something like 

$('#elem-id').magnificPopup({
        items: {
          src: '#test-popup',
          type: 'inline'
         }
       });

I hope I was able to explain my situation clearly.

Any ideas/help will be much appreciated!

Thanks,

Arnab

**Comment by pablovb** [comment]
I have a function like this, that I call once the map is painted:

```
function updateAreaScore(area, value) {
        var updatedOptions = {'areas' : {}, 'plots' : {}};
        var newPlots = {};
        var deletedPlots = [];

        var color = "red";
        if (parseFloat(value) >= parseFloat(5)) {
            color = "green";
        }

       updatedOptions.areas[area] = {
                    attrs : {
                        fill: color
                    }
                };

        $(".mapContainer").trigger('update', [updatedOptions, newPlots, deletedPlots, {animDuration : 1000}]);
}
```

But It is not working. How should I proceed? 

Thanks!
