### ISSUE TITLE
I need disable tooltips

### ISSUE THREAD

**Issue by ThiagoAlejo** [neveldo/jQuery-Mapael#290]
I will paint the areas of a map with different color, according to the values ​​assigned to it, so I need to disable the Tooltip option when these values ​​are not the ones I have in my slices available, how can I do it?

**Comment by ThiagoAlejo** [comment]
Thank you very much for your future help.

**Comment by neveldo** [comment]
Hello,

I don't understand your issue since f you don't set tooltip options for a specif area or a set of areas, the tooltip will not be displayed. Maybe you could  provide a JSFiddle example of your code ?

**Comment by ThiagoAlejo** [comment]
In my project, I want to create profiles, where areas that are not assigned for review are disabled. When passing the mouse by the specific area I want to appear a box with the information of the area, and in the case that these areas are not assigned should not take any action. This parameter I want to change according to the data that is obtained. (The value parameter is not fixed)

**Comment by Indigo744** [comment]
@ThiagoAlejo do you still need help? Did you make it work?
