### ISSUE TITLE
Map Hardware and Software Requirements

### ISSUE THREAD

**Issue by gerwin123** [neveldo/jQuery-Mapael#293]
Hello sir, may i know what is the software and hardware requirements in the using Jquery mapael. Thanks a lot.

**Comment by adeacetis** [comment]
Hello @gerwin123,
The answer lies in project README.
```
Mapael supports all modern browsers and Internet Explorer 9+. For older versions of IE, you can load jQuery 1.11.x and Raphael.js 2.1.2 as dependencies, most of the jQuery Mapael features should work fine.
```
As long as you can run a web browser, it should work. No matter the hardware you want to run your app/site on. There's no such things as hardware requirements. However, if you want to run it on mobile, you'd have to make your UI (SVG inlcuded) responsive. Performance reduction can be observed on handled devices when there's too much of SVG animation/transformation.

**Comment by gerwin123** [comment]
ok thanksss
