### ISSUE TITLE
Trigger legend click manually

### ISSUE THREAD

**Issue by stefanoberetta** [neveldo/jQuery-Mapael#294]
Hi! Awesome plugin! :D
Is there a way (or even a trick) to trigger the click on a legend element?
I want the legend to be "more custom" and the fastest way for my case is to hide the builted-in legend and to built my own legend outside the svg and attach the standard legend events to the new html elements.

Thank you very much
S

**Comment by neveldo** [comment]
Hello @stefanoberetta 

Thanks, I'm glad you appreciate Mapael ! This is not a very clean solution, but what about this ?

    .areaLegend {
        display: none;
    }

To hide the default legend generated by Mapael.

And then, in your custom legend, trigger clicks on the hidden legend items, for instance the third one (where data-index = 2) : 

    $(".areaLegend text[data-index='2']").trigger('click');

You can check this solution on this example : https://rawgit.com/neveldo/jQuery-Mapael/2.1.0/examples/basic/legend_areas.html .

**Comment by stefanoberetta** [comment]
You saved my day!
## **THANK YOU!**

**Comment by neveldo** [comment]
I'm glad it helped you !
