### ISSUE TITLE
Reset fill of previously clicked area when new one is clicked

### ISSUE THREAD

**Issue by angelcj** [neveldo/jQuery-Mapael#295]
Pretty simple question, I guess.

RIght now I have this:

        eventHandlers: {
            click: function (e, id, mapElem) {
            
            if(jQuery('.map-data[data-map="'+ id +'"]')) {
              jQuery('.map-data').hide();
              jQuery('.map-data[data-map="'+ id +'"]').fadeIn();
            }
            
            var newData = {
              'areas': {}
            };

            newData.areas[id] = {
              attrs: {
                fill: "#405273"
              }
            };
            
            jQuery(".mapcontainer").trigger('update', [{mapOptions: newData}]);
          }
        }

But of course that does reset the previously clicked area.

Is there a way to do this? I haven't found any in the examples.

Thanks!

**Comment by neveldo** [comment]
Hello @angelcj ,

Could you detail what you want to achieve ? (maybe you have a JSFiddle snippet ?)

I think the 'update' event should not reset the previously clicked areas as you only update one.

**Comment by angelcj** [comment]
Yeah that's the issue. How can I both change the color of a clicked area while reverting of previously clicked one to the default color?

So, the default color is grey. If you click an area, it changes to blue. If you click another area, I want the one that's blue to turn grey, and the newly clicked to turn blue.

I have to say I'm kind of a newbie so it might be simple but I could see a way to "reset" all areas except the clicked to the default color.

Thanks

**Comment by neveldo** [comment]
Ok I got it : I think you could store the previous clicked area in a varialbe outside the callback. You will be able to re-set the original background-color of this area (if it exists) through your newData object in the event.

**Comment by angelcj** [comment]
I solved it, so yeah, it can be closed. Thanks!

**Comment by anandprataprao** [comment]
Reset fill of previously clicked area when new one is clicked
how can i do that please give me the hint of  code
