### ISSUE TITLE
Zoom on area and hide others

### ISSUE THREAD

**Issue by mxhryvo** [neveldo/jQuery-Mapael#297]
Hey,
I would like to know how I can create a map, where when I click on one Area, it zooms in on that and disables/hides the others areas and then loads plots that are on that part of the map (on the area).

So like when you click on a district of New York( e.g. Manhattan) and then hides the other districts and loads the plots only of Manhattan (e.g. Restaurants and bars). Maybe there is a button to go back to the main view of all areas.
Or do I have to make an extra .html for every district? but then there wouldnt be the smooth feeling of a zoom, because the new site has to load. 

I have not found anything like that in the examples.
Sorry if thats shown anywhere before.

Thanks in advance.

**Comment by neveldo** [comment]
Hello @mxhryvo ,

Sorry for my very late answer ! I have made a map that fit almost what you need some time ago, feel free to check the code : https://www.vincentbroute.fr/carte-elections-regionales-2010/

Feel free to ask if you have any question !

**Comment by mxhryvo** [comment]
thanks, thats exactly what I needed. But does this also work when I wanted to extend Mapael by basic Raphael stuff? Do you know how I could draw main roads on the map that are only seen when clicked on the specific region?

Thanks for the awesome help. ;)

**Comment by neveldo** [comment]
Of course it will also work if you draw the main roads through SVG paths over the map (despite Mapael is not very suitable for this kind of stuff, as it would be tedious to draw all the roads with paths). You can take a look at this can sample where I drawn some random circles and paths over the map : https://rawgit.com/neveldo/jQuery-Mapael/2.1.0/examples/advanced/afterInit_extend_raphael_paper.html .

**Comment by Indigo744** [comment]
@mxhryvo do you still need help or can we close this issue?
