### ISSUE TITLE
I can´t use raw html on areas content with maps

### ISSUE THREAD

**Issue by FabianVCH** [neveldo/jQuery-Mapael#299]
I have an area like this:
"MN": {
   "text": {
        "content": "<span class="some class">MN (8)</span>",
        "position": null
    },
    "attrs": {
        "fill": "#bababa"
     },
    "href": null,
    "attrsHover": {
        "fill": "#ffce34"
    }
}
If I use that area like that the content data is read as a normal string it didn´t recognize the html, but if I use it on a tooltip for example it works.

**Comment by neveldo** [comment]
Hi @FabianVCH ,

This is because the tooltip is displayed within a regular HTML div, so you can freel add HTML content. However, the text attribute aims to create a Text SVG node on the map, in wich you cannot add HTML content but only raw text.

**Comment by Indigo744** [comment]
@FabianVCH can we close this issue or do you need more information?
