### ISSUE TITLE
Create My Own Custom Map via svg file

### ISSUE THREAD

**Issue by RushirajDYadav** [neveldo/jQuery-Mapael#30]
Hello Sir, 

I have downloaded your jquery Mapael library which perfectly fits to one of my current projects requirements . 

Well the examples are helpful enough to understand the implementation scenarios . 

Basically i would like to give me bit of explanation on how i can convert and svg file to the usable js so that i can plot my svg data with your library. 

Any help would be really helpfull. 

Thanx in advance

**Comment by neveldo** [comment]
Hello,

Here is a complete documentation for creating a map for mapael : http://www.vincentbroute.fr/mapael/create-map.php

**Comment by irwing** [comment]
Hello, I want to create a map for mapael but not consigos options http://www.vincentbroute.fr/mapael/create-map.php in Inkscape tutorial I have version 2.8. Can you help me?
