### ISSUE TITLE
Troubles editing content

### ISSUE THREAD

**Issue by jandresg** [neveldo/jQuery-Mapael#300]
I've been trying to edit the content box for a map that I'm and I wish to indent the subtopics after the first 2 header lines. I've been trying to play with the styling in the content line but I can't seem to succeed with it, am i missing something or can it not be done?

**Comment by neveldo** [comment]
Hi,

Do you have any JSFiddle of your work to show ? In theory, you can use all the HTML & CSS you want within the tooltips as there is no restriction. For your use case, I think you could set some imbricated ul/li.

**Comment by Indigo744** [comment]
@jandresg do you still need help or can we close this issue?
