### ISSUE TITLE
Static SVG from map

### ISSUE THREAD

**Issue by lvalladares** [neveldo/jQuery-Mapael#302]
Hello!

I want to know if its possible to make the map a static image in some conditions.

My use case is: I want to have an interactive map where i can select countries and access to some info about the countries, this info is dinamic and is readed from a database (so far so good) BUT when you access from a mobile device i want to make the map a static image but this image should look like the map (the same countries highlighted)

I cant use a static image replacemente because the countries in the map will change often, so i was wonderin if there is any way i can tell mapael to generate a static SVG based on the actual overlay.

Thanks!

**Comment by neveldo** [comment]
Hello,

Mapael is fully compatible with mobile devices. If you still need to display a static image, you may take a look at canvg : https://github.com/canvg/canvg (more info here : https://stackoverflow.com/questions/3975499/convert-svg-to-image-jpeg-png-etc-in-the-browser ) . It seems that it can be done without additional library, see here : https://stackoverflow.com/questions/28226677/save-inline-svg-as-jpeg-png-svg

**Comment by Indigo744** [comment]
@lvalladares do you still need help or can we close this issue?

**Comment by lvalladares** [comment]
I solved it with other library, thanks for your help.
