### ISSUE TITLE
Problem in firefox when updating the map

### ISSUE THREAD

**Issue by Smithangshu** [neveldo/jQuery-Mapael#304]
Hi,

I am facing an issue that is when I am updating very fast as data is coming though websocket and I need to add new plot to the map and remove plots which are older than 5 second in every 1000 ms, its working but become very slow in Firefox but in rest of the browser including IE, Chrome its working nicely. Even it takes long to show tooltip when I move mouse to any area or plot also zooming become very slow.

**Comment by neveldo** [comment]
Hello,

Could you provide a working example of your project (or maybe just a JSFidlle that highlights the issue ?).

Have you tried to increase the delay of 1000ms if it's possible ? 

Is the option 'replaceOptions' set to false when you trigger the 'update' event ?

**Comment by Indigo744** [comment]
Firefox is known to have a slower JS engine than Chrome (and IE, sometimes).
Things may get a little bit better with the new Firefox Quantum.

However, I'm sure there are some stuff we could improve on.
Can you be a little more specific on your setup?
How many plots do you have on the map at once? How many do you add/remove per update?

Thanks.

**Comment by Indigo744** [comment]
@Smithangshu we would be interested to have more information on your usage

**Comment by Indigo744** [comment]
Feel free to reopen this issue if you want to help us improve performance.
