### ISSUE TITLE
The map class `map` doesn't exists

### ISSUE THREAD

**Issue by monnie** [neveldo/jQuery-Mapael#305]
Hi there!

I have installed jquery-mapael via bower and out of the box jquery.mapael.js throws an error at line 136 "The map class `map` doesn't exists". It could be that I've missed something in the setup. All of the dependencies installed and I can confirm I've copied the minimal html and js to display the map. Any ideas what could cause this error and where I should look to debug? 

Thank you!

**Comment by monnie** [comment]
Hi again,

I was able to resolve it by changing .container in the example to .map-container, so probably just a mismatch/typo on my part. Looking forward to working with this plugin!

**Comment by neveldo** [comment]
Hi ! Thanks for having shared the answer :)
