### ISSUE TITLE
Not responsive

### ISSUE THREAD

**Issue by Vortelf** [neveldo/jQuery-Mapael#309]
Hello,
I'm trying to make a map and display it on various devices, but that is not possible because the object gets it's sizes form the map config and they are pretty much hard-coded this way.

Also the resize functon I found on an issue here is not working, gives an error.

**Comment by neveldo** [comment]
Hello,

The size within the map file stands for compute the ratio between the original SVG size and the final size of the map displayed within the container. If your map container doesn't have a fixed width, it will be responsive as well.

**Comment by Indigo744** [comment]
Mapael is responsive: https://rawgit.com/neveldo/jQuery-Mapael/2.1.0/examples/basic/minimal_example.html
Go ahead and resize the window. The map size will adapt to the window size.

So I suspect an issue on your side, either the Mapael configuration or your CSS.
