### ISSUE TITLE
How to Convert latitude,longitude to x,y  for use getCoords

### ISSUE THREAD

**Issue by rassh82** [neveldo/jQuery-Mapael#31]
I not  understand to fill the getCoords() function for creating new maps 
I creating the SVG map from Inkscape  and how to I Convert latitude,longitude to x,y

I would be grateful for any input or suggestions

**Comment by neveldo** [comment]
Hello,

Here is a complete documentation for creating your own map for Mapael : http://www.vincentbroute.fr/mapael/create-map.php
