### ISSUE TITLE
Combine range selection and legend, based on different criteria

### ISSUE THREAD

**Issue by drexel75** [neveldo/jQuery-Mapael#317]
Is it possible to combine both a range selection (slider) and a legend that would bear on different criteria on a same Mapael ?
For example, the slider would select cities based on population and the legend would filter out cities based on altitude above sea level.
Thanks for your help!

**Comment by drexel75** [comment]
I have adressed the issue with array values. 
Consider it solved !
Thanks

**Comment by neveldo** [comment]
Hi, @drexel75 

Nice, this is indeed the aim of the multiple legends feature, thanks for having kept us informed of the solution !
