### ISSUE TITLE
Can someone disable zoom but enable panning ?

### ISSUE THREAD

**Issue by george-ath** [neveldo/jQuery-Mapael#332]
The user can move (pan) the map, only when zoom is enabled.

Can someone disable zoom but enable panning ?

**Comment by Indigo744** [comment]
I didn't test it, but you may be able to achieve something similar by setting the min and max zoomlevel to the same value (e.g. 5) and setting correctly the initial zoom. THen, the user won't be able to zoom in or out, but panning should work... _I think..._

**Comment by george-ath** [comment]
Yap, that is the way that i tested it. 
But its a little heavy script that way. 
Thanks anyway!

**Comment by Indigo744** [comment]
It's just a matter of initial settings :-)

If everything is ok, please close this issue! Thanks!
