### ISSUE TITLE
[For information] Zoom issue and timing issue in Firefox

### ISSUE THREAD

**Issue by Indigo744** [neveldo/jQuery-Mapael#333]
Hello,

_I will discuss here an issue I've encounter recently which took me a while to understand. There is no question or anything, this is just for information, if someone stumble in the issue and search for it._

While developing for the enhance Zoom feature #322 & #324 , I noticed a strange issue on Firefox (or in my case, Waterfox but this is not relevant to the problem).

The zoom feature now uses the elapsed time to compute the next step (whereas before it computed all steps at once). In Chrome or IE, it works without problem. However, in my Firefox, I noticed that it was really jerky. I mean really really, you could really see the different steps.

Looking the performance window, I noticed that the animation function wasn't firing a lot (like almost every 100ms instead of the 16ms of requestAnimationFrame) and that the browser was doing nothing in between.
After adding some `console.log`, I could see that the animation function was called each 16ms, but the resulting viewbox was not changing. After more digging, it seems in fact that the elapsed time was not changing between calls. In fact, it was changing by step of 100ms!

I was baffled. We use `(new Date).getTime()` to get time, but the problem remains the same with `Date.now()` and even `performance.now()`...

In fact, I noticed that simply by typing `performance.now()` in the console would output a number with a resolution of 100ms min.
```js
performance.now()
11600
performance.now()
12400
performance.now()
13600
```

But `performance.now()` [is suppose](https://developer.mozilla.org/en-US/docs/Web/API/Performance/now) to output a high resolution timestamp as float number! What the hell...

I searched the Internet for a really long time before running into a hint, and finally finding the answer.

I finally came across this [Mozilla wiki](https://wiki.mozilla.org/Fingerprinting#Clock_skew_measurements) which talk about fingerprinting, and more importantly about clock skew measurements and adding a delay of 100ms to avoid fingerprinting the typing cadence.

Then, it unraveled rather quickly. Mozilla has implemented a list of [security and privacy features](https://wiki.mozilla.org/Security/Fingerprinting) through the TOR uplift program (i.e. to implement back specific feature from the TOR browser to Firefox). These features are hidden behind an internal flag `privacy.resistFingerprinting` (to be set in about:config).

When looking in the [list of security bugfix implemented](https://wiki.mozilla.org/Security/Fingerprinting), I finally found these two relevant tickets:
- [Animation API exposes high-res time stamp](https://bugzilla.mozilla.org/show_bug.cgi?id=1382545)
- [Reduce precision of time exposed by Javascript (Tor 1517)](https://bugzilla.mozilla.org/show_bug.cgi?id=1217238)

I remembered I activated this setting a while ago after reading some post about it. And I figured that some more privacy couldn't be harmful...

**Indeed, when using the `privacy.resistFingerprinting` option, all time values are rounded to nearest 100ms. Hence the issue in the timings, hence the issue in the zooming feature...**

_I feel better just by writing this explanation. I scratched my head really hard on this. I'm satisfied that this issue is not related to our code._

**Comment by neveldo** [comment]
Hello @Indigo744 ,

I don't use Firefox for my part, but what a great catch !! I think it was painful  to find the original source of this weird behavior ! So did you end up be de-activating these security options ?

I hope they will not be actived by default in the next version, anyway I'm glad you reported it here !

**Comment by Indigo744** [comment]
I don't think Mozilla will ever force these features by default, as it limits a lot what a website can do.
These are only for people who need an extra privacy layer.

Yeah, at the end I deactivated this option. A lot of website had weird behavior anyway. It's not _that_ worth it...

**Comment by Indigo744** [comment]
Closing this issue :)
