### ISSUE TITLE
Strange border lines in 'world_countries'

### ISSUE THREAD

**Issue by brondsem** [neveldo/jQuery-Mapael#346]
There are strange border lines that stick out into the middle of Iraq, Egypt, Ethiopia, Kenya, Argentina, etc on the Equirectangular 'world_countries' map.
![image](https://user-images.githubusercontent.com/19553/32286915-64c0efc4-bf05-11e7-8531-458e846c453a.png)

**Comment by Indigo744** [comment]
Wow, indeed! I never noticed it...
Looking [at the map closely](https://rawgit.com/neveldo/jQuery-Mapael/2.1.0/examples/advanced/dataviz_example.html), I can see it actually in a lot of place...

![image](https://user-images.githubusercontent.com/7137528/32287283-96b9ef8c-bf30-11e7-96a8-9b18d642fb28.png)
![image](https://user-images.githubusercontent.com/7137528/32287306-a9ab901e-bf30-11e7-9aa5-7f2adeef81c5.png)

@neveldo maybe we should consider making a better world map from scratch using a better source? Maybe one with more details so we could provide two versions (low and high resolution). What do you think?

**Comment by neveldo** [comment]
Hello @Indigo744 , 

I agree with you. In fact, I have already started to work on a new version of the world map some times ago. Here is the new world map that I found, which is of much better quality : https://upload.wikimedia.org/wikipedia/commons/e/e8/BlankMap-World6-Equirectangular.svg . I need to dive again into it, but I will try to finish of refining and simplify it asap !

**Comment by neveldo** [comment]
Hello @brondsem,

You can now use the world maps available here : https://github.com/neveldo/mapael-maps/tree/master/world , they should not contain strange borders anymore.

Does it solve your issue ?

**Comment by brondsem** [comment]
Yes, this is great.  A good amount of detail too!
