### ISSUE TITLE
Issue on Getting Custom Map Coords

### ISSUE THREAD

**Issue by Behseini** [neveldo/jQuery-Mapael#35]
Can you please take a look at this demo (http://jsfiddle.net/Behseini/4D645/3/) and let me know why I am not able to plot lat longs on the map?

I am using BC Canada Map in UTM zone 10 coordinates.

Thanks a lots

**Comment by Indigo744** [comment]
This has been more than one year. This thread is closed. If you have any question, feel free to open a new thread!
