### ISSUE TITLE
Not responsive in filling the space

### ISSUE THREAD

**Issue by andresteves** [neveldo/jQuery-Mapael#351]
## Description
Want the map to fill all the space but as you can see in the image it does not.
I am not using any width or heigh fixed values nor percent values.

## Expected Behavior
 - Fill all the space

## Current Behavior
<img width="962" alt="screen shot 2017-11-06 at 16 56 17" src="https://user-images.githubusercontent.com/645072/32453285-b325f5d0-c313-11e7-8a20-43e5f35b049c.png">

## Environment
* Mapael version:2.1.0
* Raphael version:2.2.7
* Browser Name and version: Safari 11.0
* Operating System and version (desktop or mobile): macOS High Sierra

**Comment by Indigo744** [comment]
@andresteves did you really wanted to close this issue or do you still need help?

**Comment by andresteves** [comment]
Yes I did. I spent hours looking at stuff but was a misspelled variable in the html code. Thanks for the quick response.

Kind Regards,
Andre
