### ISSUE TITLE
Text position on state

### ISSUE THREAD

**Issue by quizard** [neveldo/jQuery-Mapael#356]
I need to move the text over to the right and up. I've tried padding and margin but they don't seem to have an affect.           
                        
                        text: {content: "TX", attrs: {"font-size": 20, fill: "#fff", opacity:0.8  }},

Is there not an easy way to move the text content?

Thank you in advance!

**Comment by quizard** [comment]
Doh..Got it

text: {
                            content: "TX",
                            position: "left",
                            margin: 5
                        }

**Comment by neveldo** [comment]
Hi @quizard ,

I'm glad you solved your issue and brought the answer, feel free to ask if you need more help !
