### ISSUE TITLE
Error: Unknown map 'world_countries' with React

### ISSUE THREAD

**Issue by luanfonceca** [neveldo/jQuery-Mapael#362]
## Description
I am using the Mapael with React. I have just installed the package using `yarn` and started to setup the "Minimal example". But i am getting an error "Unknown map 'world_countries'", I added a `debugger` on `jquery-mapael/js/jquery-mapael.js` like 146 and print the variables and founded out that the maps property from `mapael` plugin are not loaded.

```js
# jquery-mapael/js/jquery-mapael.js+146

console.log(pluginName)
mapael

console.log($[pluginName].maps)
undefined

console.log(self.options.map.name)
"world_countries"
```

## Environment

* Mapael version: 2.1.0
* Raphael version: 2.2.7
* Browser Name and version: Google chrome
* Operating System and version (desktop or mobile): MacOSX

**Comment by luanfonceca** [comment]
I just found what was wrong in my code.

I have imported only the jquery and jquery-mapeael, but i need to import the maps that i want to use too.

```
import $ from 'jquery';
import 'jquery-mapael';
import 'jquery-mapael/js/maps/world_countries.js';
```

**Comment by neveldo** [comment]
Hi @luanfonceca ,

Great, I'm glad you solved your issue !

**Comment by luanfonceca** [comment]
I thought that i just needed to import the mapael package and the maps on Examples page would be automatically imported too, but looking at the example html i saw that you need to import it too.
