### ISSUE TITLE
Adding new plots to the maps later

### ISSUE THREAD

**Issue by ankitdholakiya** [neveldo/jQuery-Mapael#363]
## Description

I am trying to add the plots later on.

 `mapContainer = $(".mapcontainer").mapael({
        map: {
            name: mapName
            , defaultArea: {
                attrs: {
                    fill: "#fffff"
                    , stroke: "#0081c6"
                }
                , attrsHover: {
                    fill: "#fffff"
                }
            }
        }
        , zoom: {
            enabled: true,
            maxLevel: 10,
            init: {
                latitude: 40.717079,
                longitude: -74.00116,
                level: 10
            }
        },
        legend: {
            plot: {
                title: "Status",
                slices: [{
                    label: "disconnected",
                    sliceValue: "disconnected",
                    type: "image",
                    url: iconbasepath + 'marker-disconnected.png',
                    width: 50,
                    height: 40,
                    attrsHover: {
                        transform: "s1.5"
                    }
                },
                {
                    label: "faulty",
                    sliceValue: "faulty",
                    type: "image",
                    url: iconbasepath + 'marker-faulty.png',
                    width: 50,
                    height: 40,
                    attrsHover: {
                        transform: "s1.5"
                    }
                },
                {
                    label: "warning",
                    sliceValue: "warning",
                    type: "image",
                    url: iconbasepath + 'marker-warning.png',
                    width: 50,
                    height: 40,
                    attrsHover: {
                        transform: "s1.5"
                    }
                },
                {
                    label: "working",
                    sliceValue: "working",
                    type: "image",
                    url: iconbasepath + 'marker-working.png',
                    width: 50,
                    height: 40,
                    attrsHover: {
                        transform: "s1.5"
                    }
                }
                ,
                {
                    label: "unknown",
                    sliceValue: "unknown",
                    type: "image",
                    url: iconbasepath + 'marker-unknown.png',
                    width: 50,
                    height: 40,
                    attrsHover: {
                        transform: "s1.5"
                    }
                }]
            }
        }
        ,`

This is my map

This is what I am doing later on
var newPlots = {
                "AzZarqa": {
                    latitude: 32.034781,
                    longitude: 36.029991,
                    tooltip: { content: "new york" },
                    value: "unknown"
                }, "Madaba": {
                    latitude: 31.713639,
                    longitude: 35.812305,
                    tooltip: { content: "new york" },
                    value: "unknown"
                }
               , "Amman": {
                   latitude: 31.836267,
                   longitude: 35.980582,
                   tooltip: { content: "new york" },
                   value: "unknown"
               }
            };

$(".mapcontainer").trigger('update', [updatedOptions, newPlots, {}, { animDuration: 1000 }]);

But, I can not see newplots on the map, although if I am adding this new plots in initialization. Its working.

## Environment

* Mapael version: 2.1.0
* Raphael version: latest
* Browser Name and version: chrome
* Operating System and version (desktop or mobile):

**Comment by ankitdholakiya** [comment]
I got the issue resolved by this:

 ```
var updatedOptions = {
                'areas': {}, 'plots': {},
                // add some new plots ...
                newPlots: {
                    "AzZarqa": {
                        latitude: 32.034781,
                        longitude: 36.029991,
                        tooltip: { content: "new york" },
                        value: "unknown"
                    }, "Madaba": {
                        latitude: 31.713639,
                        longitude: 35.812305,
                        tooltip: { content: "new york" },
                        value: "unknown"
                    }
               , "Amman": {
                   latitude: 31.836267,
                   longitude: 35.980582,
                   tooltip: { content: "new york" },
                   value: "unknown"
               }
                },
                animDuration: 1000
            };

            $(".mapcontainer").trigger('update', updatedOptions);
``` I think it was a versioning issue.

**Comment by neveldo** [comment]
Hi @ankitdholakiya ,

You're right, the 'update' event signature have changed between the version 1.x and 2.x , thanks for having provided the answer !
