### ISSUE TITLE
Disable mouse events on plots

### ISSUE THREAD

**Issue by senojeel** [neveldo/jQuery-Mapael#365]
I am wanting to disable any mouse events over a plot. I am using the area hover for the information I want. I just want the plots there as markers. What is the best way to achieve this. Here is the Fiddle I have been working with.

http://jsfiddle.net/senojeel/nbv4myg5/11/

Thanks!

**Comment by senojeel** [comment]
I figured it out. I was able to use css and pointer-events:none. I didn't see earlier that the plots had a class.

**Comment by neveldo** [comment]
Great, thanks for having provided the answer !
