### ISSUE TITLE
Plot image zooming

### ISSUE THREAD

**Issue by senojeel** [neveldo/jQuery-Mapael#367]
I've seen the other posts about zooming with the plot point, but I can't figure it out. Can someone take a look and give me some direction? Here is my Fiddle without any of the zooming attempts.
http://jsfiddle.net/senojeel/nbv4myg5/14/

Thanks!

**Comment by senojeel** [comment]
Nevermind. Got this one to work too. I used the pull request related to the issue.

**Comment by neveldo** [comment]
Indeed, there is a pull-request open by @Indigo744 for solving this issue, I hope we will have the time to finish it soon !
