### ISSUE TITLE
How to get lat and long on click?

### ISSUE THREAD

**Issue by ankitdholakiya** [neveldo/jQuery-Mapael#369]
I just tried 
`$(".mapcontainer").data('mapael').mapPagePositionToXY(e.pageX, e.pageY)`. I am getting the x and y co-ordinates which I am saving into database.  And showing it somewhere. Now, I want to save the lat and long into database and show the same. How can I get the lat and long from the clicked position?

Currently, I am using this to get the current x and y position.
```
$(".mapcontainer").on('click', function (e) {
            
            var coords = $(".mapcontainer").data('mapael').mapPagePositionToXY(e.pageX, e.pageY), plotId = 'plot-' + Math.round(Math.random() * 1000), updateOptions = { 'newPlots': {}, 'replaceOptions': { resetPlots: true }, deletePlotKeys: plots };

            plots.push(plotId);
            updateOptions.newPlots[plotId] = {
                x: coords.x,
                y: coords.y,
                value: "unknown"
            };

            selectedlat = coords.x;
            selectedlong = coords.y;

            ReInitialize(updateOptions);

        });
```

**Comment by ankitdholakiya** [comment]
Can anyone take a look at this?

**Comment by ankitdholakiya** [comment]
This is very important feature which needs to be in consideration to mapael.

I created reverse function from the **getcoords**

For eg:
  ```
getCoords: function (lat, lon) {
                        var xfactor = 236.09023525264;
                        var xoffset = -8213.4455611814;
                        var x = (lon * xfactor) + xoffset;
                        var yfactor = -271.90876120666;
                        var yoffset = 9110.8476927967;
                        var y = (lat * yfactor) + yoffset;

                        return { 'x': x, 'y': y };
                    },
```

reverse should be:
```
 var GetLatLong = function (x, y) {
        var xoffset = 8213.4455611814;
        var xfactor = 236.09023525264;
        var longitude = (x + xoffset) / xfactor;
        var yoffset = 9110.8476927967;
        var yfactor = -271.90876120666;
        var latitude = (y - yoffset) / yfactor;
        return { 'latitude': latitude, 'longitude': longitude };
    }
```

**Comment by neveldo** [comment]
Hello @ankitdholakiya ,

You catched a lack within mapael, you are right, the reverse function of the `getCoords()` is not provided within the maps. For now, Mapael only need to retrieve the  (x, y) coordinates from a latitudes and longitudes in order to position the points on the map.

Mapael does not need the "reverse" function that would allow to get the latitude and longitude from (x, y) coordinates. It is only needed for some custom usecases as yours. That's why the maps do not provide such a reverse function by default.

However, I'm not sure that it should added to the provided maps, as it would be sparsely used I think.

**Comment by ankitdholakiya** [comment]
I think adding that function should give the more flexibility to this tool. This way the users will directly get an idea what they need to do to achieve something. I spent a whole day finding this out :)

**Comment by neveldo** [comment]
You're right, at least a little bit of documentation would be welcome on this topic :)
