### ISSUE TITLE
SVG to Mapael problem

### ISSUE THREAD

**Issue by DavidMellul** [neveldo/jQuery-Mapael#373]
## Description
Hello ! 
I would like to turn an SVG map into a Mapael script ready-to-integrate within my project.

## Expected Behavior
The SVG looks perfectly fine (edited with SVGO) and is well recognized when integrated with
 ```html 
<img src="map.svg" />
 ```
I would like Mapael to make this SVG map clickable, hoverable and with all those crazy features I can see on your website 😍 

## Current Behavior
The problem is : the map looks fine in SVG, but when used with Mapael -> only a small part is rendered... I assume this comes from a parsing / translating error in the SVG to Mapael tool.

## Environment
Last version of Mapael (2.1.0) with Raphael included before (2.2.7).
Google Chrome.
Windows 10.

## Screenshots
![image](https://user-images.githubusercontent.com/21335017/36066818-3e88c97a-0eb1-11e8-8284-f0575a7cb58a.png)

The SVG file is at this URL : https://commons.wikimedia.org/wiki/File:Montpellier_divisions_map.svg
(Github won't let me upload SVG files 😢 ) 

Thank you ! :heart:

**Comment by neveldo** [comment]
Hi @DavidMellul ,

I'm glad you use mapael for your project, and thanks for the complete description of your issue ! :)

Did you followed the tutorial available here : https://www.vincentbroute.fr/mapael/create-map.php ?

It seems that your map needs some cleaning steps through Inkscape before (or SVGO, but I don't know it).  Indeed, there are some SVG transformation applied to SVG groups(<g>), such as `transform="matrix(0.99975102,0,0,0.99975102,-456.86047,-272.17912)"` that need to be deleted. Once these transformation will be deleted within the SVG, the map will appear shifted, so you will need to to adjust the width, height and the viewbox of the SVG. 

Through Inkscape, you can easily do these cleaning steps by ungrouping all the SVG groups (you SVG will only contains a collection of simple paths). Then : `File > Document Properties > Resize page to content, and click on the “Resize page to drawing or selection”` will do the size adjustement.

**Comment by DavidMellul** [comment]
Thank you very much !!! Following your advices everything went alright. I should have been more serious with you tutorial :smiley:

**Comment by neveldo** [comment]
Great :smiley: You are welcome !
