### ISSUE TITLE
jquery mapael display text nodes on maps and access with class name

### ISSUE THREAD

**Issue by GordonOus** [neveldo/jQuery-Mapael#377]
thanks for the good work creating jquery mapael. i have an svg map that has  some text nodes for names f streets. i would like them all to be visible but generating the javascript generated has no text node. 

is there a way to get the text nodes as well since i need to access them via a classname? or do i have t extend the library t achieve that goal. if so, how do i do that. thank you

**Comment by neveldo** [comment]
Hello @GordonOus ,

I'm glad you appreciate Mapael. Indeed, the generated map must contain only the paths that define the areas available into your map.

The streets names and the other stuff should be added through Mapael options when displaying a map on a page. Take a look at this example : https://rawgit.com/neveldo/jQuery-Mapael/2.1.0/examples/basic/zoom_features.html in which there are some text labels next to the plots and within areas.

If you need more freedom for customizing your map, you still can use the "afterInit" hook in which you can manipulate the Raphael object : https://rawgit.com/neveldo/jQuery-Mapael/2.1.0/examples/advanced/afterInit_extend_raphael_paper.html



NB : Mapael is not very suitable to handle this kind of detailed maps with streets, it's more suitable for choropleth maps for instance.

**Comment by GordonOus** [comment]
thanks for that. i was able to get the texts displayed appropriately with the afterInit callback. however a new arises when i load another map dynamically in the same container. as i understand the destroy() method is called automatically. so far so good but the text nodes fro the previous maps are not removed

**Comment by neveldo** [comment]
Hello,

It's weird, the container should be fully emptied before calling mapael() on it a second time. Do you have any JSfiddle demo that highlight this issue ?

**Comment by GordonOus** [comment]
No fiddle on that. I however examined on firebug and found that streets were not cleared despite even explicitly calling destroy(). However resetting the streets to undefined everytime before loading a new map seems to do the trick for now

**Comment by neveldo** [comment]
Thanks for the update.

Feel free to re-open the issue and provide a JSfiddle demo that show the issue if you need help to find a cleaner way !
