### ISSUE TITLE
Is it possible to add shadow or stroke to outer map border only?

### ISSUE THREAD

**Issue by chavisclark** [neveldo/jQuery-Mapael#380]
## Description
I'm working on a map that requires a border styling on the entire map.

## Expected Behavior
I'd like to be able to set an option that controls styling for only the outer stroke of the map.
![map-example](https://user-images.githubusercontent.com/17089091/37980742-7123c89e-31b1-11e8-916c-7a10da0020f8.jpg)

## Current Behavior
Currently, I only see an option for setting the border for each country/area inside the map. I have not been able to successfully set a shadow or glow effect for only the outer stroke of the entire map.

## Environment
* Mapael version: 2.1.0
* Raphael version: 2.2.0
* Browser Name and version: Chrome Version 65.0.3325.181
* Operating System and version (desktop or mobile): Desktop Mac OSX El Capitan 10.11.6 (15G19009)

**Comment by chavisclark** [comment]
Closing this because I found a simple CSS solution.
`        svg {`
`-webkit-filter: drop-shadow( -2px 0px 10px #cddfe6 ); `
`filter: drop-shadow( -2px 0px 10px #cddfe6 );`
`}
`

**Comment by neveldo** [comment]
Hello @chavisclark , 

Great, I'm glad you found a solution, thanks for having shared it !
