### ISSUE TITLE
Add "showElementsWithValues" feature

### ISSUE THREAD

**Issue by phongnguyen** [neveldo/jQuery-Mapael#384]
Before submitting a new issue, please search on the issue tracker first (https://github.com/neveldo/jQuery-Mapael/issues)

## Description

* Update areas to have more than one value per value type. For example: Value type "Insurance Services" and values can be "Auto," "Life," "Home." Each area then can have one, two, or all three values.
* Add the ability to filter the map using "showElementsWithValues" event.

## Expected Behavior

* Check all the "on" values of the legend/filter bar. Loop through all the areas and turn on areas that has all the "on" values, turn off the areas that don't
* Create event "showElementsWithValues"

## Current Behavior

* If there are more than one value in the "value," the app treats them as two separate type, and each type has one value. The desired effect is that both values should belong to one type.

## Environment

* Mapael version: 2.2.0
* Raphael version: 2.2.7
* Browser Name and version: Chrome, most recent
* Operating System and version (desktop or mobile): MacOS and iOS

**Comment by neveldo** [comment]
Hi @phongnguyen ,

Ok, I thought about it, and I think there is a simple solution by defining a legend for each category. Here is a JSFiddle example : http://jsfiddle.net/neveldo/90d4gz8h/ . What do you think ?

However, it seems there is a bug when handling click, some areas that should be hidden actually aren't hidden.

I will try to investigate in the Mapael code this week-end, feel free to take a look before if you can !

**Comment by phongnguyen** [comment]
Hi Vincent,

Yea, I thought of that too. But I think the relationship currently is AND
i.e. Both Cat 1 and Cat 2 are true then highlight the area, if just one Cat
is false, the area is hidden. If we can change that relationship to OR, I
think that would fix it.

Thanks Vincent for looking into this.

Cheers,

Phong



On June 14, 2018 at 9:03:23 AM, Vincent Brouté (notifications@github.com)
wrote:

Hi @phongnguyen <https://github.com/phongnguyen> ,

Ok, I thought about it, and I think there is a simple solution by defining
a legend for each category. Here is a JSFiddle example :
http://jsfiddle.net/neveldo/90d4gz8h/ . What do you think ?

However, it seems there is a bug when handling click, some areas that
should be hidden actually aren't hidden.

I will try to investigate in the Mapael code this week-end, feel free to
take a look before if you can !

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/neveldo/jQuery-Mapael/issues/384#issuecomment-397287812>,
or mute the thread

**Comment by neveldo** [comment]
Hi @phongnguyen ,

I took a look, and there was a mistake in my code snipped. Each area must be related to as many values as legends number. As there are 3 legends (one for each category), each area must be related to the 3 values. Also, the values indexes must match with legend indexes. 
Now, it works fine, if you click on 'category2' in the legend, all areas for which the values array contain the value 'category2' for the 2nd index will be triggered.

Here is the updated JSFiddle : http://jsfiddle.net/90d4gz8h/18/

**Comment by phongnguyen** [comment]
Hi Vincent,

Thank you for looking into this. Please take a look at this screenshot:
https://www.screencast.com/t/pSZnzgmdTQ

   - I have turn everything off except for Category 2
   - The application I try to build is that any areas contain “Category 2”
   would be highlighted. That means “department-56,” “department-22,” and
   "“department-44.” Can that happen?

Cheers,

Phong



On June 18, 2018 at 2:45:41 PM, Vincent Brouté (notifications@github.com)
wrote:

Hi @phongnguyen <https://github.com/phongnguyen> ,

I took a look, and there was a mistake in my code snipped. Each area must
be related to as many values as legends number. As there are 3 legends (one
for each category), each area must be related to the 3 values. Also, the
values indexes must match with legend indexes.
Now, it works fine, if you click on 'category2' in the legend, all areas
for which the values array contain the value 'category2' for the 2nd index
will be triggered.

Here is the updated JSFiddle : http://jsfiddle.net/90d4gz8h/18/

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/neveldo/jQuery-Mapael/issues/384#issuecomment-398155867>,
or mute the thread

**Comment by neveldo** [comment]
That's the normal behavior. By default, in Mapael, click on a legend item allow to hide the matching areas. 

Of course, if you prefer to highlight the areas related to a clicked legend item instead of hiding them, you can play with the attrs for highlighting the area instead of reducing their opacity (which is the default behavior from mapael).

**Comment by neveldo** [comment]
Hi @phongnguyen , did you manage to find a solution ?

**Comment by phongnguyen** [comment]
Hi Vincent,

Yea, we’re going with the add/remove classes route:
https://phong.azurewebsites.net/areas-we-serve.html

Thanks for checking in and answering my questions!

Phong



On July 2, 2018 at 6:33:05 AM, Vincent Brouté (notifications@github.com)
wrote:

Hi @phongnguyen <https://github.com/phongnguyen> , did you manage to find a
solution ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/neveldo/jQuery-Mapael/issues/384#issuecomment-401757376>,
or mute the thread

**Comment by neveldo** [comment]
Great result @phongnguyen , I'm glad it helped you !
