### ISSUE TITLE
Programmatically click on a region

### ISSUE THREAD

**Issue by maxime-kouemo** [neveldo/jQuery-Mapael#389]
Hi. 
Thank you guys for your incredible library. I am using it in an android app. The thing is that, as my map has some many little regions, it would be nice for the users to be able to search a region, by its id and the to press on a button that will call a js function that will simulate a click on region. Is there a way to realize this?`function programmaticallyClickOnRegion(regionID){
        //search the region by ID
        //if the region exists, launch a click event on the region
}`

Thanks in advance.

**Comment by neveldo** [comment]
Hi @maxime-kouemo ,

Thank you, you are welcome, I'm glad you appreciate Mapael !

If you want to trigger a click event on a region or a plot of your map, I should be able to do it with the trigger()function from jQuery, for instance : 

```
$(".area[data-id='department-29']").trigger('click');
```

I hope it will help you !

**Comment by maxime-kouemo** [comment]
It works flawlessly.
