### ISSUE TITLE
Paramètres Mapael Population depuis base de données

### ISSUE THREAD

**Issue by umair10** [neveldo/jQuery-Mapael#39]
Bonjour,
Avant tout bravo pour le plugin il est excellent ! 
Lors de l'utilisation du plugin j'ai utilisé la carte des départements avec la population et la je suis confronté à un problème.
je souhaite récupérer les valeurs de la population depuis une BDD et les insérer avec une boucle. 
Pour ce faire je récupère tout mes départements avec leurs noms, numéro et population que je met dans un tableau javascript que je souhaite utilisé dans le paramètre 
areas
Voila le Fiddle : http://jsfiddle.net/neveldo/TUYHN/

**Comment by chrisk59** [comment]
Je rebondis sur ce topic en français 8-), je viens de découvrir Mapael et je dois dire que j'adopte ! ehehe. mais jai une question, qu'elle serait la meilleur façon de mettre à jours mes informations depuis une db, genre avoir le nombre d habitant d'un département depuis une db mysql, donc j'imagine rapatrier cela avant le chargement de la map..
Merci d'avance pour vos réponses.

**Comment by neveldo** [comment]
Bonjour,

Content que vous appréciez Mapael ;) Oui vous pouvez tout à fait récupérer les données à afficher depuis votre base, les charger par exemple dans un objet JSON côté serveur, puis les manipuler en Javascript pour construire votre carte !

**Comment by Indigo744** [comment]
Bonjour! Ce topic va être clos. Si vous avez une question, vous pouvez ouvrir un nouveau fil :)
