### ISSUE TITLE
Split areas

### ISSUE THREAD

**Issue by Sherbert99** [neveldo/jQuery-Mapael#392]
Hi on the world map (Equirectangular projection) when I hover over France in Europe I don't want French Guiana to highlight in South America. What would be the best way to make this happen? Do I have to split the coordinates from the current FR coordinates? If so do the separate coordinates for France and French Guiana already exist somewhere? Thanks

**Comment by Sherbert99** [comment]
I figured it out. I just opened the map in Lnkscape and broke apart the path and exported a new map. That was easier than trying to spit the coordinates manually. Thanks!

**Comment by neveldo** [comment]
Hi @Sherbert99 , 

I think you found the easiest way to do it, I would have suggested the same ! Thanks for having shared the answer !
