### ISSUE TITLE
Top of the world map looks squeezed

### ISSUE THREAD

**Issue by ecemac** [neveldo/jQuery-Mapael#395]
First of all thank you for the amazing work!

I'm trying to create an interactive world map with Mapael, however it kind of looks crammed at the top. It looks okay below Russia. I'm guessing it has something to do with my following question:

I can't seem to make the map full screen. I did everything according to issue #76 but it doesn't work.

You can see what I mean here: 
https://jsfiddle.net/ecemac/nyamhg4j/13/

I'm using the latest versions of Mapael and Raphael.

I would really appreciate the help since I'm on the edge of a breakdown 😢

**Comment by neveldo** [comment]
Hello @ecemac ,

I think this is more a matter of the projection used in the 'world_countries' map (Equirectangular one). You can this on this demo page that the top of the world also looks squeezed : https://www.vincentbroute.fr/mapael/try.html .

There are other projections available, feel free to check them in the file examples/basic/multiple_projections.html I think the miller projection could fit your need as it looks more natural.

**Comment by ecemac** [comment]
lol I didn't think it would be so simple, thank you so much!

**Comment by neveldo** [comment]
I'm glad it helped you !
