### ISSUE TITLE
Handling click event on image

### ISSUE THREAD

**Issue by eldiego34** [neveldo/jQuery-Mapael#42]
Hi again, i'm triying to execute a function on a click event of a image, here is my code:

<code>
		actualizarMapa = function(a,b,c,d){
			// add some new plots ...
			var updatedOptions = {'images' : {}};
			updatedOptions.images['image1'] = {
				'src' : 'img/img02.png',
				'latitude' : '-34.27083595',
				'longitude' : '-66.54968262',
				'width':80,
				'height':80
			};
			updatedOptions.images['image2'] = {
				'src' : 'img/img01.png',
				'latitude' : '-32.15701249',
				'longitude' : '-65.67077637',
				'width':80,
				'height':80
			};
			
			var newPlots = [];
			// and delete some others ...
			var deletedPlots = [b];
			$(".maparea1").trigger('update', [updatedOptions,newPlots, deletedPlots, {animDuration : 1000, 
				afterUpdate:function(container, paper, areas, plots, options){
					var mapConf = $.fn.mapael.maps['sanluis_departments'], coords = {};
					for (var id in options.images) {
						coords = mapConf.getCoords(options.images[id].latitude, options.images[id].longitude);
						paper.image(options.images[id].src, coords.x - options.images[id].width / 2, coords.y - options.images[id].height / 2, options.images[id].width, options.images[id].height);
					}
				}
			}]);
		}
</code>

I could put a pointer cursor via CSS, but i cant handle the click event in the image, do you have any ideas? Can i add a new attr to the image object?

**Comment by Indigo744** [comment]
Hey! It has been more than one year. I'm closing this thread. Feel free to submit a new issue if you have any problems.
