### ISSUE TITLE
I can not update legend

### ISSUE THREAD

**Issue by ruby232** [neveldo/jQuery-Mapael#43]
I need to update legend but not have options, any idea.

**Comment by tonyDarriens** [comment]
Hi @neveldo 

I need to update the legend as well. I looked the plugin code but I must confess I still didn't figured out how to make a workaround. 

Are you planning to make a function to update the legend?

**Comment by neveldo** [comment]
Hello,

Unfortunately, I didn't planned to add this function in a short term, but I add it to the todo. Not the best solution but in order to refresh the legend, you could refresh the entire map by emptying the appropriate DIV container and calling again $.mapael()with the new options.

**Comment by RASMiranda** [comment]
Hey,
> you could refresh the entire map by emptying the appropriate DIV container and calling again $.mapael()with the new options

I tried exactly this with ajax, but don't know if it's because of my map, but after the first 5 updates page starts getting slow and the browser not responding...
Legend update would be really really cool, bump this!

**Comment by Indigo744** [comment]
This feature is implemented in upcoming version 2.0. Closing this thread.
