### ISSUE TITLE
What to do with calculated coordinates?

### ISSUE THREAD

**Issue by demogorgorn** [neveldo/jQuery-Mapael#45]
Hello! Thanks for great jquery plugin. I have read your explanaitions at https://github.com/neveldo/jQuery-Mapael/issues/11 about how to get coords for the getCoords function. And here is my silly question what to do with calculated coords? 

I mean that i used your formula to calculate and my result is:

6 = ax * 19.647687 + bx
483 = ax * -169.932400 + bx

the same procedure i will make for y. And then what? Where to place these datas? Also i misunderstand how to use calculator at http://ncalculators.com/algebra/2-variable-equation-solver.htm. Thank you very much for the answer!

**Comment by shahzadasaeed** [comment]
Hi Neveldo,

I am using this for one of my project. but i am confusing in Coordinates system that is How we can calculate X1, Y1??

Thanks

**Comment by neveldo** [comment]
Hi,

All the steps are explained in this tutorial : http://www.vincentbroute.fr/mapael/create-map.php , did you check it ?

**Comment by Indigo744** [comment]
Thread close. Open a new thread if you have another issue.
