### ISSUE TITLE
Load PHP file as tooltip

### ISSUE THREAD

**Issue by thatguymason** [neveldo/jQuery-Mapael#47]
Hi, I was wondering if there was any way load a PHP file in the tooltip of a plot? Any help would be appreciated. My thinking is that it would end up looking something like this:
```javascript
'lancaster' : {
    latitude: 40.0399754, 
    longitude: -76.300349,
    tooltip: {content: "<php include 'lancaster.php'; ?>"},
    value: 'lancaster'
}
```
or maybe even:
```javascript
tooltip: {content: 'lancaster.php', content-type: PHP}
```

**Comment by thatguymason** [comment]
Nevermind, I think I figured out the best way to do it with simple old jQuery after a little brainstorming:
```
$.get("assets/lancaster.php", function(data){ 
    $(".mapcontainer").trigger("update", [{ plots: {'lancaster': { tooltip: {content: data} } } }]);
});
```

**Comment by thatguymason** [comment]
Alright so I was able to implement pulling from other documents via this method:
```
'lancaster': {
    latitude: 40.0399754, 
    longitude: -76.300349,
    tooltip: { content: "assets/lancaster.php", type: "GET" },
    value: "lancaster"
}
```

by changing the source code:
```
if (options.tooltip.type && options.tooltip.type == "GET") {
    $.get(options.tooltip.content, function(data){
        elem.mapElem.tooltipContent = data;
    });
} else {
    elem.mapElem.tooltipContent = options.tooltip.content;
}
```

**Comment by neveldo** [comment]
Hello,

Thanks for your suggestion that allows to load content asynchronously in the tooltips. I will check it when as soon as I will work on the next version !

**Comment by Zaheer-Abbas** [comment]
i am creating as user register on our site a plot has to display on country from where user belongs but how i can implement plot with php mysql

**Comment by Zaheer-Abbas** [comment]
<?php 
require('db.php');

$sql = "select * from signup";
$result = mysql_query($sql);

while($row = mysql_fetch_assoc($result)){
?>	

<script>



$(function(){
	$(".container").mapael({
	map : {
	name : "world_countries",
	defaultArea: {
	attrs : {
	stroke : "#5C5C5C", 
	"stroke-width" : 1,
	fill:"#000",
	},
	}
	},

	plots: {
	'pk' : {
     latitude: 35.717079,
	 longitude: -80.00116,
	 size:5,
	 marginLeft: 30,
	 tooltip: {content :" <?php echo $row['firstname'] ?>"},
     value: "50586757"
     },

       

	   defaultArea: {

				attrs : {

					fill : "#f4f4e8"

					, stroke: "#ced8d0"

				}

				, attrsHover : {

					fill: "#a4e100"

				}

				, text : {

					attrs : {

						fill : "#505444"

					}

					, attrsHover : {

						fill : "#000"

					}

				}

			}

		},

	   

	
	});

});




 
</script>

	
   <?php
}


 ?>

I create this type of code that working but while loop , looping just one time ..

**Comment by Zaheer-Abbas** [comment]
in above comment world map code in mapael not displaying in between while loop

**Comment by neveldo** [comment]
Hello, 

It seems that it's more a PHP issue than a mapael one. Your code seems to be right, maybe you have inserted only a single row in your table ?
