### ISSUE TITLE
SVG Map 

### ISSUE THREAD

**Issue by hy-liad** [neveldo/jQuery-Mapael#49]
Hullo Vicent, I have downloaded an SVG map for Africa (following steps at: http://www.vincentbroute.fr/mapael/create-map.php). I'm stuck from there. I intend to highlight only eight sections (countries): Burundi, Ethiopia, Kenya, Rwanda, Tanzania, South Africa, Uganda, Other countries as rest of Africa. Will appreciate any help offered!
Thank you

**Comment by neveldo** [comment]
Hello,

Have you managed to generate the JS map from your SVG file by following the tutorial ? I need more details from where you are stuck in order to help you. Maybe you could show me the problem through a JSFiddle example ?

**Comment by gomuap** [comment]
Hello Vincent,

i have taken the world countries...I intended to zoom in and zoom out the map(it is happening).Here I do want to zoom only the map not the font size (while zooming the country name too increasing the size).. shall I know how could achieve this? Thank you

**Comment by Indigo744** [comment]
Please open a new issue if needed.
