### ISSUE TITLE
Legend does not appear with IE10

### ISSUE THREAD

**Issue by mimi19** [neveldo/jQuery-Mapael#51]
Hello,
Legend area does not appear only in IE10.
Thank you for your help,
Best Regards

**Comment by neveldo** [comment]
Hello,

It will be hard to help you without any details, could you provide an example that reproduces the problem with IE10 ? (you can use JSFiddle)

Thank you

**Comment by mimi19** [comment]
Bonjour,

Je n'utilise pas JSFiddle.

Sur IE10, la légende s'affichait correctement avec la librairie JS "jquery.mapael" de mars 2014.
Depuis, que nous avons fait la mise à jour (supprimé et réintégré) avec la version de janvier 2015 alors la légende ne s'affiche plus sur IE10.
--> J'ai le même problème, si j'installe le module complet (download version 1.0.0) disponible sur votre site http://www.vincentbroute.fr/mapael/

Merci pour votre aide,
Cordialement,




________________________________
De : Vincent Brouté [mailto:notifications@github.com]
Envoyé : samedi 11 avril 2015 17:54
À : neveldo/jQuery-Mapael
Cc : RAEDLE Mireille
Objet : Re: [jQuery-Mapael] Legend does not appear with IE10 (#51)


Hello,

It will be hard to help you without any details, could you provide an example that reproduces the problem with IE10 ? (you can use JSFiddle)

Thank you

-

**Comment by neveldo** [comment]
Bonjour,

Avez-vous une erreur JS dans la console ? Pourriez-vous poster la configuration de votre map pour essayer d'y trouver le problème ? (si vous ne souhaitez pas la rendre publique, vous pouvez me l'envoyer par mail, mon adresse est visible ici : http://www.vincentbroute.fr)

**Comment by kikilevrai** [comment]
Bonjour, j'ai le même soucis sur IE11 et la console affiche l'erreur suivante : 

"SCRIPT5042: Variable non définie en mode strict : Fichier : jquery.mapael.js, ligne : 708, colonne : 15"

![capture](https://cloud.githubusercontent.com/assets/12165457/7385887/60aab266-ee4d-11e4-8222-7585ee74d34a.PNG)

**Comment by neveldo** [comment]
Bonjour, 

merci pour la précision, je vais regarder ça dès que possible !

**Comment by neveldo** [comment]
Fixed with the 1.0.1 release : https://github.com/neveldo/jQuery-Mapael/releases/tag/1.0.1 .
