### ISSUE TITLE
Add a link on mouseover

### ISSUE THREAD

**Issue by cgordenne** [neveldo/jQuery-Mapael#53]
Hello,

Is it possible to create a link between two plots when one of them is on mouseover ?
I'm asking that because I only see 'area' and 'plot' in the update section of the documentation.

Thanks,

**Comment by neveldo** [comment]
Hello,

You pointed out a lack in mapael : for now, it's not possible to update easily links through the update event.

However, you can draw your own links in the afterInit() function, and then make them appear on mouseover on the wanted plots. Here is a small piece of code that does the stuff : http://jsfiddle.net/neveldo/oj6p69hm/ . I hope it will help you !

**Comment by cgordenne** [comment]
Thanks a lot !

**Comment by neveldo** [comment]
Here we go : https://github.com/neveldo/jQuery-Mapael/commit/936639ddc02d194490ab501bd770ce67bead1aca … :) . 

I will create new JSFiddle use cases very soon !
