### ISSUE TITLE
mapTooltip

### ISSUE THREAD

**Issue by Drouac** [neveldo/jQuery-Mapael#54]
I want to thank you for the Mapael plugin, it is perfect for the project I am working on ! 

I have a question about the "mapTooltip", It works perfectly as the examples show, which is unfortunately not exactly what I would like. I would like to plot the legend in a fix area like this example (which is what I want but use the leaflet plugin) : http://leafletjs.com/examples/choropleth.html

I try to follow this example which use the Raphael library but I didn't suceed : https://parall.ax/blog/view/2985/tutorial-creating-an-interactive-svg-map.

Can you help me ?

**Comment by neveldo** [comment]
Hello,

Thank you, I'm glad you appreciate Mapael !Did you check this JSFiddle example : http://jsfiddle.net/neveldo/b5fj4qod/ , I think it matches with what you want to get.

**Comment by Drouac** [comment]
Thank you for the answer, I should have try it before ... I will keep you in touch when my work will be done !
