### ISSUE TITLE
Update trigger not executed on mouseout

### ISSUE THREAD

**Issue by RauchF** [neveldo/jQuery-Mapael#57]
Situation: I have an area with events bound to mouseover and mouseout, and call `$('.map').trigger('update', [ ... ])` (with different options) from those events.

Expected behaviour: The update triggers are executed as the events are fired.

Actual behaviour: The update works fine for mouseover. The mouseout update is not executed until I actually enter the area with my mouse again, which defeats the purpose of triggering an update on mouseout.

This happens regardless of browser used. I use Mapael version 1.0.0 and Raphael version 2.1.2.

edit: for clarification, the actual mouseout event is triggered, it's just the trigger('update', [ ... ]) that is called from inside the event that is not executed.

**Comment by neveldo** [comment]
Hello,

Could you provide your map configuration (or, better, an online code through JSFiddle for example) ?

**Comment by neveldo** [comment]
Hello, 

I have made some tests and I think this problem occurs because in Mapael, the "eventHandler" callbacks are bound after the internal mapael mouseover callback that triggers the attributes switching when the mouse leave an area or a circle. 

I will do some tests and fix this problem asap.

**Comment by neveldo** [comment]
Fixed by this commit : https://github.com/neveldo/jQuery-Mapael/commit/6733137d98f8d927d8b03174bcbf77601c227f5e (the fix will be in the next release).

Here is a working example on JSFiddle : http://jsfiddle.net/neveldo/oe1we4f6/

**Comment by RauchF** [comment]
Hello,

please excuse my failure to reply in time. I was without access for some time shortly after posting this issue, and missed the notification mail when clearing my backlog of mail.

Thank you for the fix though, it helps out very much!
