### ISSUE TITLE
mapael and svg-pan-zoom / touch events

### ISSUE THREAD

**Issue by scooterlord** [neveldo/jQuery-Mapael#58]
Hello!

Great work on the excellent plugin! Are there any plans to implement panning-zooming with touch events? There is an excellent library that besides touch events contains great performance improvements. I have no idea how to connect between the two, but I guess this would sky-rocket the plugin's (already high) popularity!

https://github.com/ariutta/svg-pan-zoom

**Comment by neveldo** [comment]
Hello !

I'm glad you appreciate Mapael. I agree with you, having panning and zooming features working on mobile devices would be such a great improvement. I will add it to my todos, and I will work on it as soon as possible, but feel free to contribute if you can :)

Thank for your feature suggestion !

**Comment by scooterlord** [comment]
...as posted again in another thread in here, wish my knowledge wasn't limited in this area, I would gladly help if I could :/

**Comment by neveldo** [comment]
Ok, stay tuned !

**Comment by scooterlord** [comment]
I guess it can't get any better than this, wishing for something and having it granted to you! :) Can't wait to see this done!

**Comment by grotewold** [comment]
Looking forward to an update as well. Great plugin!!

**Comment by neveldo** [comment]
Here we go :

https://github.com/neveldo/jQuery-Mapael/commit/a3a8e7e133faf5bd3b33aa763984408fb0634ac8
https://github.com/neveldo/jQuery-Mapael/commit/bf22d26bec07734bbd6e6514002fb1b933f00e1f

It will be available in the next release of mapael. The pinch zoom works fine, but unfortunately it seems to be very slow on mobile devices for now.
