### ISSUE TITLE
Area from GPS co-ordinance

### ISSUE THREAD

**Issue by martic** [neveldo/jQuery-Mapael#61]
Mapael is Awsome, I have created a custom map from wiki commons followed your tutorials. Had one issue with the gps Co-ordinance upside down, maybe because I'm in the southern hemisphere? But easily worked it out. Thanks!

My issue is, now have to match GPS co-ordinance to the local government regions on the map.
The user enters an address using google geocode api and pulls back the lat & long.
From a list of lat & long info, I need to add up all the submitted addresses within each region.

Methods to calculate this, could be:
1. I will have to collect more data to connect all the postal codes or suburbs which fall under each plot region.
Or
2. Using the co-ordinate calc I know which x & y position in the map. from this I'm hoping you could help me how to calculate the underling region.

Any help would be appreciated.

**Comment by neveldo** [comment]
Hello,

I'm glad you appreciate Mapael !

I think the best way to achieve the method 2 is to extend mapael with a function that returns the area where x,y  coordinates are in. 

You can see at Element.isPointInside(x, y) from the Raphael.js API : http://raphaeljs.com/reference.html#Element.isPointInside . 

I think the main steps should be :

1 / Convert the latitude,longitude to x,y coordinates
2 / Loop on each area (Raphael Element) of the map
3 / Check if x,y is within the current area through the isPointInside() function, and then, return this area.

I hope this will help you. I think this should be a great feature to add to mapael !
