### ISSUE TITLE
load map with one plot type active

### ISSUE THREAD

**Issue by synyoes** [neveldo/jQuery-Mapael#62]
Is there any quick fix on how to load the map with only one plot type displayed (plot showed in the map and legend in full opacity) and the rest of the plots are with opacity 0 in the map and lighter in the legend.
Hope I explained right what I want to do.
thanks

**Comment by neveldo** [comment]
Hello,

For now, Mapael haven't such an option that allows you to desactivate by default items in the legend. I think this should be a useful feature, I will try to add it to mapael as soon as possible, I think it will be an 'active' option on each legend items that will be set to true by default.

Before this new option to come, I think you could trigger a click event on all legend items you want to desactivated, just after the map initialization (there is an afterInit() hook).

Here is how to set desactivated the second item of the legend : 

$(".areaLegend text[data-index=1]").trigger('click');

I hope this will help you !

**Comment by synyoes** [comment]
It worked like a charm. 
Thank you.
