### ISSUE TITLE
maphael not fullly load in my project

### ISSUE THREAD

**Issue by satriani04** [neveldo/jQuery-Mapael#63]
i use maphael for my project but it's not fully loaded and tooltip does not appear. i followed this http://jsfiddle.net/neveldo/VqwUZ/ it work properly in my native html but not in my project.  
![maphael](https://cloud.githubusercontent.com/assets/8855315/8451264/3fe2efe4-200c-11e5-9b2d-5ba01231c9d6.png)

the plot area does not appear in bottom. i used jquery 1.7. please help me fix this problem. thanks

**Comment by neveldo** [comment]
Hello,

Do you have an online example of your code in order to help you ? It seems that there is missing CSS for the tooltip and zoom-in/zoom-out buttons (you can copy them from the top-right textarea of the JSFiddle example).

Regarding the plots legend, have  you added a <div class="plotLegend"></div> within your map container ?

**Comment by satriani04** [comment]
hello neveldo..thanks for your reply

uhm...i'm sorry, it's still in my local but i copied exactly from jsfidle, so i think there is no missing css.

its still problem inmy tooltip and plot legend. thanks

**Comment by neveldo** [comment]
Hello,

Unfortunately, I will not be able to help you without seeing your code. Could you post it through JSFiddle or another code hosting service ?

**Comment by satriani04** [comment]
hi neveldo.... i have solved my maphael in my project..

i think it have a problem with my bootstrap tab. when i turn off my bootstrap tab. maphael work completly, but when i placed it inside bootstrap tab, it become problem again.

do you have any ide how to solved it? 

thanks

**Comment by Indigo744** [comment]
Same problem than neveldo/jQuery-Mapael#72
A hidden Bootstrap tab is set to `display:none`. It's doing some weird stuff to text while loading the SVG.

I don't know if you can implement the solution I proposed in the thread. You need to override Bootstrap class that is handling the tab.

**Comment by Indigo744** [comment]
Duplicated of issue #135
