### ISSUE TITLE
click handlers on areas require two taps in iOS

### ISSUE THREAD

**Issue by dabernathy89** [neveldo/jQuery-Mapael#67]
Not sure if there is any way around this. Registering a click handler on areas works great, except on iOS. The first tap works, but after that, it requires two taps on a separate area to trigger the handler.

Example - issue is visible in iOS or iOS simulator in Xcode:
https://jsfiddle.net/dabernathy89/3q8w0akr/embedded/result/

**Comment by dabernathy89** [comment]
I may have spoken too soon - just needed to register a 'touchstart' handler as well.

**Comment by neveldo** [comment]
Hello,

Thank to have brought the solution !
