### ISSUE TITLE
After yesterday's update the links are not working correctly.

### ISSUE THREAD

**Issue by nkchaverri** [neveldo/jQuery-Mapael#68]
If you go to this link: http://jsfiddle.net/neveldo/yckqj78q/ the link example just shows the first link but not the others, is it possible to fix this.  BTW I love the plugin !

**Comment by chaverri** [comment]
+1 http://prntscr.com/8ant87

**Comment by neveldo** [comment]
Hello,

Thank you for reporting this issue ! I will fix it as soon as possible. It should work fine with the last stable release (1.0.1).

**Comment by neveldo** [comment]
Fixed :)
