### ISSUE TITLE
How to make it responsive

### ISSUE THREAD

**Issue by MPMathieu** [neveldo/jQuery-Mapael#70]
Hi Vincent.
How to fit the entire card responsive?
Thx

**Comment by MPMathieu** [comment]
Hi Vincent.
How to fit the entire card responsive?
Thx

**Comment by neveldo** [comment]
Hi,

I don't understand your issue, could you explain it more, or provide a JSFiddle example ?

**Comment by Indigo744** [comment]
@MPMathieu did you solve your problem? If so, can you close this thread? Thanks!

**Comment by Indigo744** [comment]
It's been 1 week. Closing this thread.
