### ISSUE TITLE
Request: include minify version of js files

### ISSUE THREAD

**Issue by Indigo744** [neveldo/jQuery-Mapael#71]
Hello,

I love Mapael.

Here is a simple little request: provide minify version of all your JS file!
For instance: jquery.mapael.min.js

Thanks a lot!

**Comment by neveldo** [comment]
Hello,

Thank you for the suggestion, I will provide it, by waiting, you can use a tool such as YUI Compressor in your project in order to minify JS.

**Comment by Indigo744** [comment]
Maybe implement it for Mapael 2.0.0 ;-)

**Comment by neveldo** [comment]
I will do it for the 2.0.0 :) I'm just wondering if we should provide a static minified version of mapael (which should be updated manually in the repository before publishing a new release) or if we should set up a grunt build script that automatically minify the JS. Maybe the second option will be better.

**Comment by Indigo744** [comment]
The automatic grunt build is best if you already have a grunt environment ready.

**Comment by neveldo** [comment]
Done : https://github.com/neveldo/jQuery-Mapael/commit/eaff3bbbc6e15662d2a088be150667c44a7a5dc1 . I also added a Grunfile.js in order to run minification and jshint check automatically : https://github.com/neveldo/jQuery-Mapael/commit/ad145899e8b4a86ae671bcd4b88b4b8bd82e0705

**Comment by Indigo744** [comment]
Perfect :-)
