### ISSUE TITLE
Allow to set the animation duration for click on legend label

### ISSUE THREAD

**Issue by Indigo744** [neveldo/jQuery-Mapael#73]
As for now, the duration value when clicking on a legend label is hard coded to 300ms.
```javascript
elems[id].mapElem.animate({"opacity":legendOptions.hideElemsOnClick.opacity}, 300, "linear", ...
```
This value should be customizable, just like with `AttrsHover.animDuration`.

I suggest adding an option in `hideElemsOnClick.animDuration`.

**Comment by neveldo** [comment]
Hello,

You are right, this value should be customizable through an option. I add this item to the todo for the next version ! Feel free to make a pull request if you can do it ;)

**Comment by Indigo744** [comment]
Never done a pull request... But I will try if I find enough time :-)
Any information on the next release (when/what)?

**Comment by Indigo744** [comment]
Ok so I tried something. Is it ok?

**Comment by neveldo** [comment]
Hello,

It's ok, I just merged your pull request to the repository, many thanks for your contribution !

**Comment by Indigo744** [comment]
Glad I could help :-)
This was my first ^^
