### ISSUE TITLE
RequireJS support?

### ISSUE THREAD

**Issue by carlosrusso** [neveldo/jQuery-Mapael#74]
jQuery-Mapael currently assumes that jQuery and Raphael are declared globally and does not support RequireJS out of the box.
An approach like http://simonsmith.io/writing-amd-compatible-plugins-for-jquery/ could be followed to address this.

**Comment by neveldo** [comment]
Hello,

Thank you for the suggestion and the link, I think this is a good idea too. I will make Mapael AMD compatible asap !

**Comment by neveldo** [comment]
Done : https://github.com/neveldo/jQuery-Mapael/commit/56f941f5ce03254a4cb65963860a9868a6813da9

Could you give me a feedback with your project ?

**Comment by carlosrusso** [comment]
Sure! I'll try it as soon as I can!

**Comment by Indigo744** [comment]
@carlosrusso : any update? 
Can you close this thread if issue is resolved? Thanks :)
