### ISSUE TITLE
Add version number as public variable

### ISSUE THREAD

**Issue by Indigo744** [neveldo/jQuery-Mapael#78]
It would be good if Mapael provide the current version in a public variable, for instance accessible by `Mapael.version`.

I can think of several use cases for such information:
 - allow people to build plugins on top of Mapael for a certain version
 - check current version and github version for updates

Of course, you will need to remember to modify this variable each time you release a new version.

Example of implementation (that I use) : DataTables (jQuery plugin):
```
	/**
	 * Version string for plug-ins to check compatibility. Allowed format is
	 * `a.b.c-d` where: a:int, b:int, c:int, d:string(dev|beta|alpha). `d` is used
	 * only for non-release builds. See http://semver.org/ for more information.
	 *  @member
	 *  @type string
	 *  @default Version number
	 */
	DataTable.version = "1.10.10-dev";
```
See https://github.com/DataTables/DataTables

**Comment by neveldo** [comment]
Hello,

Thank for the proposal, I think this is a good idea. I'm currently working on making mapael AMD compatible (see https://github.com/neveldo/jQuery-Mapael/issues/74), I will add version information once this is done.

**Comment by neveldo** [comment]
Done : https://github.com/neveldo/jQuery-Mapael/commit/56f941f5ce03254a4cb65963860a9868a6813da9#diff-8ff6272a968b1eb5b5ca8302c0ed73bfR16

**Comment by Indigo744** [comment]
Perfect :-)
