### ISSUE TITLE
Issue with Trigger Update Link

### ISSUE THREAD

**Issue by fulhamrugby** [neveldo/jQuery-Mapael#86]
Hi, Trying to utilise the update link function, however not having an extreme amount of luck - everything else works apart from the link, should it be:

		var updatedOptions = {'areas' : {}, 'plots' : {}};
		updatedOptions.areas[endcountry] = {
			attrs: {
				fill : "#C1D034",transform : "s1.05"
			}
		};
		
	// add some new plots ...
		var newPlots = {
		"destination" : {
			type : "image",url :"image/dest.jpeg",
			width: 30,
			height: 20,
				latitude : dlat,
				longitude : dlong
				}
				 };

				var opt = {animDuration : 2000,
					elemOptions : {
						'link1' : {
		                factor : -0.3
		                // The source and the destination of the link can be set with a latitude and a longitude or a x and a y ...
		                , between : [{latitude : 24.708785, longitude : -5.402427}, {x : 560, y : 280}]
		                , attrs : { "stroke-width" : 2  }
		            }
							}
				};

		$(".container").trigger('update', [updatedOptions, newPlots, opt]);

or

		var updatedOptions = {'areas' : {}, 'plots' : {}, 'links' : {}};
		updatedOptions.areas[endcountry] = {
			attrs: {
				fill : "#C1D034",transform : "s1.05"
			}
		};
		updatedOptions.links = {
			'link1' : {
                factor : -0.3
                // The source and the destination of the link can be set with a latitude and a longitude or a x and a y ...
                , between : [{latitude : 24.708785, longitude : -5.402427}, {x : 560, y : 280}]
                , attrs : {
                    "stroke-width" : 2
                }
                , tooltip: {content : "Link"}
            }
		};

	// add some new plots ...
		var newPlots = {
		"destination" : {
			type : "image",url :"image/dest.jpeg",
			width: 30,
			height: 20,
				latitude : dlat,
				longitude : dlong
				}
				 };

				var opt = {animDuration : 2000};

		$(".container").trigger('update', [updatedOptions, newPlots, opt]);

really cool tool btw

**Comment by fulhamrugby** [comment]
Hi,

Don't Worry - Figured it, but it may be helpful for some examples:

	var updatedOptions = {'areas' : {}, 'plots' : {}, 'links' : {}};
		updatedOptions.areas[endcountry] = {
			attrs: {
				fill : "#C1D034",transform : "s1.05"
			}
		};
		
	// add some new plots ...
		var newPlots = {
		"destination" : {
			type : "image",url :"image/dest.jpeg",
			width: 30,
			height: 20,
				latitude : dlat,
				longitude : dlong
				}
				 };

				var link = {
						'link1' : {
		                factor : -0.3
		                // The source and the destination of the link can be set with a latitude and a longitude or a x and a y ...
		                , between : [{latitude : 24.708785, longitude : -5.402427}, {x : 560, y : 280}]
		                , attrs : { "stroke-width" : 2  }
		            }
				};
				var deletedPlots = {};

		$(".container").trigger('update', [updatedOptions, newPlots, deletedPlots, {animDuration :2000, newLinks:link}]);

**Comment by neveldo** [comment]
Hello,

Thank for the reply, I'm glad you found the answer. (ps : did you checked this example with links update : http://jsfiddle.net/neveldo/dk3ers47/ ?)

**Comment by fulhamrugby** [comment]
Hi again, 

Trying to use the deleted links option, for the links I inserted Dynamically. I have basically copied your jquery but it is not working:

function reset() {
	// Update some plots and areas attributes ...
		var updatedOptions = {
			'areas' : {},
			'plots' : {},
			'links' : {},
		}
		, opt = {
			animDuration : 1000,
			'deletedLinks' : ['parcel']
		};

		// and delete some others ...
		var deletedPlots = [];

		$(".container").trigger('update', [updatedOptions, {}, [], opt]);
	var logobj = JSON.stringify(opt);
	console.log("Deleting Links: "+logobj);
	}

**Comment by fulhamrugby** [comment]
manipulating the jsfiddle exmple suggests you can't delete dynamically created links

**Comment by neveldo** [comment]
Hello,

There was a bug, I just fixed it : https://github.com/neveldo/jQuery-Mapael/commit/d0ec9a1c2664c68831c991c167c3716cac70da74 . It should now work fine if you download the fixed version of Mapael from Master.

Here is a working JSFiddle (where I put the fixed code of Mapael) : http://jsfiddle.net/neveldo/ta16ns9c/ .

**Comment by Nkadze** [comment]
Hi I've got exactly same issue with deleting dynamically added links, now it's fixed when I tried with fixed version, but newLinks stroke color seems to be broken, before it was working with option:
```javascript
attrs : { 
        stroke: "#89ff72",
	    "stroke-width" : 2
	  }
```
but now it's using default blue color for link ignoring my stroke: "#89ff72"

**Comment by neveldo** [comment]
Hello,

Thank you for reporting this side effect, it's now fixed : https://github.com/neveldo/jQuery-Mapael/commit/689c8ffe3a3e09733820409ebf239b64d8c027dc . Here is the updated JSFiddle example : http://jsfiddle.net/neveldo/ta16ns9c/ .

**Comment by fulhamrugby** [comment]
Great thanks, all working well.

**Comment by Nkadze** [comment]
Hi, yes link colors are fixed, but tooltip locations are incorrect now

**Comment by neveldo** [comment]
Hi,

This is due to a recent improvement made on tooltip position on master branch : https://github.com/neveldo/jQuery-Mapael/pull/81

The tooltip position should now be absolute instead of fixed in the CSS. The map container should be relative. Here is a JSFiddle example : http://jsfiddle.net/c9hzegpv/

**Comment by Nkadze** [comment]
thanks it was helpful!
